run:
  concurrency: 4
  modules-download-mode: readonly
  tests: true

linters:
  disable-all: true

  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - inamedparam
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    #    - mnd
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    # todo: fix
    #    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tenv
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  asasalint:
    use-builtin-exclusions: false
  copyloopvar:
    check-alias: true
  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: true
  exhaustive:
    default-signifies-exhaustive: true
  forbidigo:
    forbid:
      - self
      - this
    exclude-godoc-examples: false
  goconst:
    ignore-tests: true
  godot:
    capital: true
  gofmt:
    simplify: false
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
  gomoddirectives:
    exclude-forbidden: true
  gomodguard:
    blocked:
      modules:
        - github.com/golang/protobuf:
            recommendations:
              - google.golang.org/protobuf
        - github.com/satori/go.uuid:
            recommendations:
              - github.com/google/uuid
        - github.com/gofrs/uuid:
            recommendations:
              - github.com/gofrs/uuid/v5
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  inamedparam:
    skip-single-param: true
  loggercheck:
    require-string-key: true
  makezero:
    always: true
  nolintlint:
    require-explanation: true
    require-specific: true
  perfsprint:
    strconcat: false
  tenv:
    all: true
  wrapcheck:
    ignoreSigs:
      - func errors.New(text string) error
      - .Error(
      - .Errorf(
      - (context.Context).Err()
