services:
  postgres:
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fastad}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fastad}
      POSTGRES_DB: ${POSTGRES_DB:-fastad}
    volumes:
      - ./vol/db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-fastad} -d ${POSTGRES_DB:-fastad}
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
