services:
  data-service:
    build:
      context: .
      dockerfile: docker/data_service/Dockerfile
    environment:
      FASTAD_DATA_SERVICE_DEBUG: 1
      FASTAD_DATA_SERVICE_LISTEN_ADDRESS: 0.0.0.0:1337

      FASTAD_DATA_SERVICE_POSTGRES_USER: ${POSTGRES_USER:-fastad}
      FASTAD_DATA_SERVICE_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fastad}
      FASTAD_DATA_SERVICE_POSTGRES_DATABASE: ${POSTGRES_DB:-fastad}
      FASTAD_DATA_SERVICE_POSTGRES_HOST: postgres
    ports:
      - "127.0.0.1:1337:1337"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-fastad}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fastad}
      POSTGRES_DB: ${POSTGRES_DB:-fastad}
    volumes:
      - ./vol/db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-fastad} -d ${POSTGRES_DB:-fastad}
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
