// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: data/services/services.proto

package services

import (
	durationpb1 "github.com/planetscale/vtprotobuf/types/known/durationpb"
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *Service_Batch) CloneVT() *Service_Batch {
	if m == nil {
		return (*Service_Batch)(nil)
	}
	r := new(Service_Batch)
	if rhs := m.Services; rhs != nil {
		tmpContainer := make([]*Service, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Services = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Service_Batch) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *Service_Checker_Action) CloneVT() *Service_Checker_Action {
	if m == nil {
		return (*Service_Checker_Action)(nil)
	}
	r := new(Service_Checker_Action)
	r.Action = m.Action
	r.Timeout = (*durationpb.Duration)((*durationpb1.Duration)(m.Timeout).CloneVT())
	r.RunCount = m.RunCount
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Service_Checker_Action) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *Service_Checker) CloneVT() *Service_Checker {
	if m == nil {
		return (*Service_Checker)(nil)
	}
	r := new(Service_Checker)
	r.Type = m.Type
	r.Path = m.Path
	r.DefaultTimeout = (*durationpb.Duration)((*durationpb1.Duration)(m.DefaultTimeout).CloneVT())
	if rhs := m.Actions; rhs != nil {
		tmpContainer := make([]*Service_Checker_Action, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Actions = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Service_Checker) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *Service) CloneVT() *Service {
	if m == nil {
		return (*Service)(nil)
	}
	r := new(Service)
	r.Id = m.Id
	r.Name = m.Name
	r.Checker = m.Checker.CloneVT()
	r.DefaultScore = m.DefaultScore
	r.Disabled = m.Disabled
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Service) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *ListRequest) CloneVT() *ListRequest {
	if m == nil {
		return (*ListRequest)(nil)
	}
	r := new(ListRequest)
	r.Version = m.Version.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *ListRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *ListResponse) CloneVT() *ListResponse {
	if m == nil {
		return (*ListResponse)(nil)
	}
	r := new(ListResponse)
	r.Version = m.Version.CloneVT()
	if rhs := m.Services; rhs != nil {
		tmpContainer := make([]*Service, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Services = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *ListResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *CreateBatchRequest) CloneVT() *CreateBatchRequest {
	if m == nil {
		return (*CreateBatchRequest)(nil)
	}
	r := new(CreateBatchRequest)
	if rhs := m.Services; rhs != nil {
		tmpContainer := make([]*Service, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Services = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *CreateBatchRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *CreateBatchResponse) CloneVT() *CreateBatchResponse {
	if m == nil {
		return (*CreateBatchResponse)(nil)
	}
	r := new(CreateBatchResponse)
	if rhs := m.Services; rhs != nil {
		tmpContainer := make([]*Service, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Services = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *CreateBatchResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (this *Service_Batch) EqualVT(that *Service_Batch) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Services) != len(that.Services) {
		return false
	}
	for i, vx := range this.Services {
		vy := that.Services[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Service{}
			}
			if q == nil {
				q = &Service{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Service_Batch) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*Service_Batch)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Service_Checker_Action) EqualVT(that *Service_Checker_Action) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Action != that.Action {
		return false
	}
	if !(*durationpb1.Duration)(this.Timeout).EqualVT((*durationpb1.Duration)(that.Timeout)) {
		return false
	}
	if this.RunCount != that.RunCount {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Service_Checker_Action) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*Service_Checker_Action)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Service_Checker) EqualVT(that *Service_Checker) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Type != that.Type {
		return false
	}
	if this.Path != that.Path {
		return false
	}
	if !(*durationpb1.Duration)(this.DefaultTimeout).EqualVT((*durationpb1.Duration)(that.DefaultTimeout)) {
		return false
	}
	if len(this.Actions) != len(that.Actions) {
		return false
	}
	for i, vx := range this.Actions {
		vy := that.Actions[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Service_Checker_Action{}
			}
			if q == nil {
				q = &Service_Checker_Action{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Service_Checker) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*Service_Checker)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Service) EqualVT(that *Service) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Id != that.Id {
		return false
	}
	if this.Name != that.Name {
		return false
	}
	if !this.Checker.EqualVT(that.Checker) {
		return false
	}
	if this.DefaultScore != that.DefaultScore {
		return false
	}
	if this.Disabled != that.Disabled {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Service) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*Service)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ListRequest) EqualVT(that *ListRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.Version.EqualVT(that.Version) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ListRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*ListRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ListResponse) EqualVT(that *ListResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Services) != len(that.Services) {
		return false
	}
	for i, vx := range this.Services {
		vy := that.Services[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Service{}
			}
			if q == nil {
				q = &Service{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if !this.Version.EqualVT(that.Version) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ListResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*ListResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *CreateBatchRequest) EqualVT(that *CreateBatchRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Services) != len(that.Services) {
		return false
	}
	for i, vx := range this.Services {
		vy := that.Services[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Service{}
			}
			if q == nil {
				q = &Service{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CreateBatchRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*CreateBatchRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *CreateBatchResponse) EqualVT(that *CreateBatchResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Services) != len(that.Services) {
		return false
	}
	for i, vx := range this.Services {
		vy := that.Services[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Service{}
			}
			if q == nil {
				q = &Service{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CreateBatchResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*CreateBatchResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
