// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/services/services_service.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_data_services_services_service_proto protoreflect.FileDescriptor

const file_data_services_services_service_proto_rawDesc = "" +
	"\n" +
	"$data/services/services_service.proto\x12\rdata.services\x1a\x1cdata/services/services.proto2\xef\x01\n" +
	"\x0fServicesService\x12?\n" +
	"\x04List\x12\x1a.data.services.ListRequest\x1a\x1b.data.services.ListResponse\x12T\n" +
	"\vCreateBatch\x12!.data.services.CreateBatchRequest\x1a\".data.services.CreateBatchResponse\x12E\n" +
	"\x06Update\x12\x1c.data.services.UpdateRequest\x1a\x1d.data.services.UpdateResponseB\xb5\x01\n" +
	"\x11com.data.servicesB\x14ServicesServiceProtoP\x01Z5github.com/c4t-but-s4d/fastad/pkg/proto/data/services\xa2\x02\x03DSX\xaa\x02\rData.Services\xca\x02\rData\\Services\xe2\x02\x19Data\\Services\\GPBMetadata\xea\x02\x0eData::Servicesb\x06proto3"

var file_data_services_services_service_proto_goTypes = []any{
	(*ListRequest)(nil),         // 0: data.services.ListRequest
	(*CreateBatchRequest)(nil),  // 1: data.services.CreateBatchRequest
	(*UpdateRequest)(nil),       // 2: data.services.UpdateRequest
	(*ListResponse)(nil),        // 3: data.services.ListResponse
	(*CreateBatchResponse)(nil), // 4: data.services.CreateBatchResponse
	(*UpdateResponse)(nil),      // 5: data.services.UpdateResponse
}
var file_data_services_services_service_proto_depIdxs = []int32{
	0, // 0: data.services.ServicesService.List:input_type -> data.services.ListRequest
	1, // 1: data.services.ServicesService.CreateBatch:input_type -> data.services.CreateBatchRequest
	2, // 2: data.services.ServicesService.Update:input_type -> data.services.UpdateRequest
	3, // 3: data.services.ServicesService.List:output_type -> data.services.ListResponse
	4, // 4: data.services.ServicesService.CreateBatch:output_type -> data.services.CreateBatchResponse
	5, // 5: data.services.ServicesService.Update:output_type -> data.services.UpdateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_services_services_service_proto_init() }
func file_data_services_services_service_proto_init() {
	if File_data_services_services_service_proto != nil {
		return
	}
	file_data_services_services_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_services_services_service_proto_rawDesc), len(file_data_services_services_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_services_services_service_proto_goTypes,
		DependencyIndexes: file_data_services_services_service_proto_depIdxs,
	}.Build()
	File_data_services_services_service_proto = out.File
	file_data_services_services_service_proto_goTypes = nil
	file_data_services_services_service_proto_depIdxs = nil
}
