// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/services/services.proto

package services

import (
	checker "github.com/c4t-but-s4d/fastad/pkg/proto/checker"
	version "github.com/c4t-but-s4d/fastad/pkg/proto/data/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Checker       *Service_Checker       `protobuf:"bytes,3,opt,name=checker,proto3" json:"checker,omitempty"`
	DefaultScore  float64                `protobuf:"fixed64,4,opt,name=default_score,json=defaultScore,proto3" json:"default_score,omitempty"`
	Disabled      bool                   `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_data_services_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_data_services_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_data_services_services_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetChecker() *Service_Checker {
	if x != nil {
		return x.Checker
	}
	return nil
}

func (x *Service) GetDefaultScore() float64 {
	if x != nil {
		return x.DefaultScore
	}
	return 0
}

func (x *Service) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *version.Version       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_data_services_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_services_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_data_services_services_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Version       *version.Version       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_data_services_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_services_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_data_services_services_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListResponse) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type CreateBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBatchRequest) Reset() {
	*x = CreateBatchRequest{}
	mi := &file_data_services_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchRequest) ProtoMessage() {}

func (x *CreateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_services_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateBatchRequest) Descriptor() ([]byte, []int) {
	return file_data_services_services_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBatchRequest) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type CreateBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBatchResponse) Reset() {
	*x = CreateBatchResponse{}
	mi := &file_data_services_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchResponse) ProtoMessage() {}

func (x *CreateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_services_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateBatchResponse) Descriptor() ([]byte, []int) {
	return file_data_services_services_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBatchResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Disabled      *bool                  `protobuf:"varint,2,opt,name=disabled,proto3,oneof" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_data_services_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_services_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_data_services_services_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Version       *version.Version       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_data_services_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_services_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_data_services_services_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *UpdateResponse) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type Service_Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service_Batch) Reset() {
	*x = Service_Batch{}
	mi := &file_data_services_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_Batch) ProtoMessage() {}

func (x *Service_Batch) ProtoReflect() protoreflect.Message {
	mi := &file_data_services_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_Batch.ProtoReflect.Descriptor instead.
func (*Service_Batch) Descriptor() ([]byte, []int) {
	return file_data_services_services_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Service_Batch) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type Service_Checker struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Type           checker.Type              `protobuf:"varint,1,opt,name=type,proto3,enum=checker.Type" json:"type,omitempty"`
	Path           string                    `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	DefaultTimeout *durationpb.Duration      `protobuf:"bytes,3,opt,name=default_timeout,json=defaultTimeout,proto3" json:"default_timeout,omitempty"`
	Actions        []*Service_Checker_Action `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Service_Checker) Reset() {
	*x = Service_Checker{}
	mi := &file_data_services_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_Checker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_Checker) ProtoMessage() {}

func (x *Service_Checker) ProtoReflect() protoreflect.Message {
	mi := &file_data_services_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_Checker.ProtoReflect.Descriptor instead.
func (*Service_Checker) Descriptor() ([]byte, []int) {
	return file_data_services_services_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Service_Checker) GetType() checker.Type {
	if x != nil {
		return x.Type
	}
	return checker.Type(0)
}

func (x *Service_Checker) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Service_Checker) GetDefaultTimeout() *durationpb.Duration {
	if x != nil {
		return x.DefaultTimeout
	}
	return nil
}

func (x *Service_Checker) GetActions() []*Service_Checker_Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Service_Checker_Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        checker.Action         `protobuf:"varint,1,opt,name=action,proto3,enum=checker.Action" json:"action,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RunCount      int64                  `protobuf:"varint,3,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service_Checker_Action) Reset() {
	*x = Service_Checker_Action{}
	mi := &file_data_services_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_Checker_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_Checker_Action) ProtoMessage() {}

func (x *Service_Checker_Action) ProtoReflect() protoreflect.Message {
	mi := &file_data_services_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_Checker_Action.ProtoReflect.Descriptor instead.
func (*Service_Checker_Action) Descriptor() ([]byte, []int) {
	return file_data_services_services_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Service_Checker_Action) GetAction() checker.Action {
	if x != nil {
		return x.Action
	}
	return checker.Action(0)
}

func (x *Service_Checker_Action) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Service_Checker_Action) GetRunCount() int64 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

var File_data_services_services_proto protoreflect.FileDescriptor

const file_data_services_services_proto_rawDesc = "" +
	"\n" +
	"\x1cdata/services/services.proto\x12\rdata.services\x1a\x1egoogle/protobuf/duration.proto\x1a\x15checker/checker.proto\x1a\x1adata/version/version.proto\"\xb3\x04\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\achecker\x18\x03 \x01(\v2\x1e.data.services.Service.CheckerR\achecker\x12#\n" +
	"\rdefault_score\x18\x04 \x01(\x01R\fdefaultScore\x12\x1a\n" +
	"\bdisabled\x18\x05 \x01(\bR\bdisabled\x1a;\n" +
	"\x05Batch\x122\n" +
	"\bservices\x18\x01 \x03(\v2\x16.data.services.ServiceR\bservices\x1a\xcb\x02\n" +
	"\aChecker\x12!\n" +
	"\x04type\x18\x01 \x01(\x0e2\r.checker.TypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12B\n" +
	"\x0fdefault_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0edefaultTimeout\x12?\n" +
	"\aactions\x18\x04 \x03(\v2%.data.services.Service.Checker.ActionR\aactions\x1a\x83\x01\n" +
	"\x06Action\x12'\n" +
	"\x06action\x18\x01 \x01(\x0e2\x0f.checker.ActionR\x06action\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1b\n" +
	"\trun_count\x18\x03 \x01(\x03R\brunCount\">\n" +
	"\vListRequest\x12/\n" +
	"\aversion\x18\x01 \x01(\v2\x15.data.version.VersionR\aversion\"s\n" +
	"\fListResponse\x122\n" +
	"\bservices\x18\x01 \x03(\v2\x16.data.services.ServiceR\bservices\x12/\n" +
	"\aversion\x18\x02 \x01(\v2\x15.data.version.VersionR\aversion\"H\n" +
	"\x12CreateBatchRequest\x122\n" +
	"\bservices\x18\x01 \x03(\v2\x16.data.services.ServiceR\bservices\"I\n" +
	"\x13CreateBatchResponse\x122\n" +
	"\bservices\x18\x01 \x03(\v2\x16.data.services.ServiceR\bservices\"M\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\bdisabled\x18\x02 \x01(\bH\x00R\bdisabled\x88\x01\x01B\v\n" +
	"\t_disabled\"s\n" +
	"\x0eUpdateResponse\x120\n" +
	"\aservice\x18\x01 \x01(\v2\x16.data.services.ServiceR\aservice\x12/\n" +
	"\aversion\x18\x02 \x01(\v2\x15.data.version.VersionR\aversionB\xae\x01\n" +
	"\x11com.data.servicesB\rServicesProtoP\x01Z5github.com/c4t-but-s4d/fastad/pkg/proto/data/services\xa2\x02\x03DSX\xaa\x02\rData.Services\xca\x02\rData\\Services\xe2\x02\x19Data\\Services\\GPBMetadata\xea\x02\x0eData::Servicesb\x06proto3"

var (
	file_data_services_services_proto_rawDescOnce sync.Once
	file_data_services_services_proto_rawDescData []byte
)

func file_data_services_services_proto_rawDescGZIP() []byte {
	file_data_services_services_proto_rawDescOnce.Do(func() {
		file_data_services_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_services_services_proto_rawDesc), len(file_data_services_services_proto_rawDesc)))
	})
	return file_data_services_services_proto_rawDescData
}

var file_data_services_services_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_data_services_services_proto_goTypes = []any{
	(*Service)(nil),                // 0: data.services.Service
	(*ListRequest)(nil),            // 1: data.services.ListRequest
	(*ListResponse)(nil),           // 2: data.services.ListResponse
	(*CreateBatchRequest)(nil),     // 3: data.services.CreateBatchRequest
	(*CreateBatchResponse)(nil),    // 4: data.services.CreateBatchResponse
	(*UpdateRequest)(nil),          // 5: data.services.UpdateRequest
	(*UpdateResponse)(nil),         // 6: data.services.UpdateResponse
	(*Service_Batch)(nil),          // 7: data.services.Service.Batch
	(*Service_Checker)(nil),        // 8: data.services.Service.Checker
	(*Service_Checker_Action)(nil), // 9: data.services.Service.Checker.Action
	(*version.Version)(nil),        // 10: data.version.Version
	(checker.Type)(0),              // 11: checker.Type
	(*durationpb.Duration)(nil),    // 12: google.protobuf.Duration
	(checker.Action)(0),            // 13: checker.Action
}
var file_data_services_services_proto_depIdxs = []int32{
	8,  // 0: data.services.Service.checker:type_name -> data.services.Service.Checker
	10, // 1: data.services.ListRequest.version:type_name -> data.version.Version
	0,  // 2: data.services.ListResponse.services:type_name -> data.services.Service
	10, // 3: data.services.ListResponse.version:type_name -> data.version.Version
	0,  // 4: data.services.CreateBatchRequest.services:type_name -> data.services.Service
	0,  // 5: data.services.CreateBatchResponse.services:type_name -> data.services.Service
	0,  // 6: data.services.UpdateResponse.service:type_name -> data.services.Service
	10, // 7: data.services.UpdateResponse.version:type_name -> data.version.Version
	0,  // 8: data.services.Service.Batch.services:type_name -> data.services.Service
	11, // 9: data.services.Service.Checker.type:type_name -> checker.Type
	12, // 10: data.services.Service.Checker.default_timeout:type_name -> google.protobuf.Duration
	9,  // 11: data.services.Service.Checker.actions:type_name -> data.services.Service.Checker.Action
	13, // 12: data.services.Service.Checker.Action.action:type_name -> checker.Action
	12, // 13: data.services.Service.Checker.Action.timeout:type_name -> google.protobuf.Duration
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_data_services_services_proto_init() }
func file_data_services_services_proto_init() {
	if File_data_services_services_proto != nil {
		return
	}
	file_data_services_services_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_services_services_proto_rawDesc), len(file_data_services_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_services_services_proto_goTypes,
		DependencyIndexes: file_data_services_services_proto_depIdxs,
		MessageInfos:      file_data_services_services_proto_msgTypes,
	}.Build()
	File_data_services_services_proto = out.File
	file_data_services_services_proto_goTypes = nil
	file_data_services_services_proto_depIdxs = nil
}
