// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pinger/pinger_service.proto

package pinger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pinger_pinger_service_proto protoreflect.FileDescriptor

const file_pinger_pinger_service_proto_rawDesc = "" +
	"\n" +
	"\x1bpinger/pinger_service.proto\x12\x06pinger\x1a\x13pinger/pinger.proto2B\n" +
	"\rPingerService\x121\n" +
	"\x04Ping\x12\x13.pinger.PingRequest\x1a\x14.pinger.PingResponseB\x88\x01\n" +
	"\n" +
	"com.pingerB\x12PingerServiceProtoP\x01Z.github.com/c4t-but-s4d/fastad/pkg/proto/pinger\xa2\x02\x03PXX\xaa\x02\x06Pinger\xca\x02\x06Pinger\xe2\x02\x12Pinger\\GPBMetadata\xea\x02\x06Pingerb\x06proto3"

var file_pinger_pinger_service_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: pinger.PingRequest
	(*PingResponse)(nil), // 1: pinger.PingResponse
}
var file_pinger_pinger_service_proto_depIdxs = []int32{
	0, // 0: pinger.PingerService.Ping:input_type -> pinger.PingRequest
	1, // 1: pinger.PingerService.Ping:output_type -> pinger.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pinger_pinger_service_proto_init() }
func file_pinger_pinger_service_proto_init() {
	if File_pinger_pinger_service_proto != nil {
		return
	}
	file_pinger_pinger_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pinger_pinger_service_proto_rawDesc), len(file_pinger_pinger_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pinger_pinger_service_proto_goTypes,
		DependencyIndexes: file_pinger_pinger_service_proto_depIdxs,
	}.Build()
	File_pinger_pinger_service_proto = out.File
	file_pinger_pinger_service_proto_goTypes = nil
	file_pinger_pinger_service_proto_depIdxs = nil
}
