// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: pinger/pinger.proto

package pinger

import (
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *PingRequest) CloneVT() *PingRequest {
	if m == nil {
		return (*PingRequest)(nil)
	}
	r := new(PingRequest)
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *PingRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *PingResponse) CloneVT() *PingResponse {
	if m == nil {
		return (*PingResponse)(nil)
	}
	r := new(PingResponse)
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *PingResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}
