// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: receiver/receiver_service.proto

package receiver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_receiver_receiver_service_proto protoreflect.FileDescriptor

const file_receiver_receiver_service_proto_rawDesc = "" +
	"\n" +
	"\x1freceiver/receiver_service.proto\x12\breceiver\x1a\x17receiver/receiver.proto2\xa0\x01\n" +
	"\x0fReceiverService\x12J\n" +
	"\vSubmitFlags\x12\x1c.receiver.SubmitFlagsRequest\x1a\x1d.receiver.SubmitFlagsResponse\x12A\n" +
	"\bGetState\x12\x19.receiver.GetStateRequest\x1a\x1a.receiver.GetStateResponseB\x96\x01\n" +
	"\fcom.receiverB\x14ReceiverServiceProtoP\x01Z0github.com/c4t-but-s4d/fastad/pkg/proto/receiver\xa2\x02\x03RXX\xaa\x02\bReceiver\xca\x02\bReceiver\xe2\x02\x14Receiver\\GPBMetadata\xea\x02\bReceiverb\x06proto3"

var file_receiver_receiver_service_proto_goTypes = []any{
	(*SubmitFlagsRequest)(nil),  // 0: receiver.SubmitFlagsRequest
	(*GetStateRequest)(nil),     // 1: receiver.GetStateRequest
	(*SubmitFlagsResponse)(nil), // 2: receiver.SubmitFlagsResponse
	(*GetStateResponse)(nil),    // 3: receiver.GetStateResponse
}
var file_receiver_receiver_service_proto_depIdxs = []int32{
	0, // 0: receiver.ReceiverService.SubmitFlags:input_type -> receiver.SubmitFlagsRequest
	1, // 1: receiver.ReceiverService.GetState:input_type -> receiver.GetStateRequest
	2, // 2: receiver.ReceiverService.SubmitFlags:output_type -> receiver.SubmitFlagsResponse
	3, // 3: receiver.ReceiverService.GetState:output_type -> receiver.GetStateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_receiver_receiver_service_proto_init() }
func file_receiver_receiver_service_proto_init() {
	if File_receiver_receiver_service_proto != nil {
		return
	}
	file_receiver_receiver_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_receiver_receiver_service_proto_rawDesc), len(file_receiver_receiver_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_receiver_receiver_service_proto_goTypes,
		DependencyIndexes: file_receiver_receiver_service_proto_depIdxs,
	}.Build()
	File_receiver_receiver_service_proto = out.File
	file_receiver_receiver_service_proto_goTypes = nil
	file_receiver_receiver_service_proto_depIdxs = nil
}
