// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: receiver/receiver.proto

package receiver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlagResponse_Verdict int32

const (
	FlagResponse_VERDICT_UNSPECIFIED FlagResponse_Verdict = 0
	FlagResponse_VERDICT_ACCEPTED    FlagResponse_Verdict = 1
	FlagResponse_VERDICT_OWN         FlagResponse_Verdict = 2
	FlagResponse_VERDICT_OLD         FlagResponse_Verdict = 3
	FlagResponse_VERDICT_INVALID     FlagResponse_Verdict = 4
)

// Enum value maps for FlagResponse_Verdict.
var (
	FlagResponse_Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_ACCEPTED",
		2: "VERDICT_OWN",
		3: "VERDICT_OLD",
		4: "VERDICT_INVALID",
	}
	FlagResponse_Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"VERDICT_ACCEPTED":    1,
		"VERDICT_OWN":         2,
		"VERDICT_OLD":         3,
		"VERDICT_INVALID":     4,
	}
)

func (x FlagResponse_Verdict) Enum() *FlagResponse_Verdict {
	p := new(FlagResponse_Verdict)
	*p = x
	return p
}

func (x FlagResponse_Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlagResponse_Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_receiver_receiver_proto_enumTypes[0].Descriptor()
}

func (FlagResponse_Verdict) Type() protoreflect.EnumType {
	return &file_receiver_receiver_proto_enumTypes[0]
}

func (x FlagResponse_Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlagResponse_Verdict.Descriptor instead.
func (FlagResponse_Verdict) EnumDescriptor() ([]byte, []int) {
	return file_receiver_receiver_proto_rawDescGZIP(), []int{1, 0}
}

type SubmitFlagsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flags []string `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
}

func (x *SubmitFlagsRequest) Reset() {
	*x = SubmitFlagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receiver_receiver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFlagsRequest) ProtoMessage() {}

func (x *SubmitFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_receiver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFlagsRequest.ProtoReflect.Descriptor instead.
func (*SubmitFlagsRequest) Descriptor() ([]byte, []int) {
	return file_receiver_receiver_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitFlagsRequest) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

type FlagResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag       string               `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Verdict    FlagResponse_Verdict `protobuf:"varint,2,opt,name=verdict,proto3,enum=receiver.FlagResponse_Verdict" json:"verdict,omitempty"`
	Message    string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	FlagPoints float64              `protobuf:"fixed64,4,opt,name=flag_points,json=flagPoints,proto3" json:"flag_points,omitempty"`
}

func (x *FlagResponse) Reset() {
	*x = FlagResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receiver_receiver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagResponse) ProtoMessage() {}

func (x *FlagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_receiver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagResponse.ProtoReflect.Descriptor instead.
func (*FlagResponse) Descriptor() ([]byte, []int) {
	return file_receiver_receiver_proto_rawDescGZIP(), []int{1}
}

func (x *FlagResponse) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *FlagResponse) GetVerdict() FlagResponse_Verdict {
	if x != nil {
		return x.Verdict
	}
	return FlagResponse_VERDICT_UNSPECIFIED
}

func (x *FlagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FlagResponse) GetFlagPoints() float64 {
	if x != nil {
		return x.FlagPoints
	}
	return 0
}

type SubmitFlagsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*FlagResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *SubmitFlagsResponse) Reset() {
	*x = SubmitFlagsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_receiver_receiver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitFlagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFlagsResponse) ProtoMessage() {}

func (x *SubmitFlagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_receiver_receiver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFlagsResponse.ProtoReflect.Descriptor instead.
func (*SubmitFlagsResponse) Descriptor() ([]byte, []int) {
	return file_receiver_receiver_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitFlagsResponse) GetResponses() []*FlagResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_receiver_receiver_proto protoreflect.FileDescriptor

var file_receiver_receiver_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x46, 0x6c, 0x61,
	0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x22,
	0x88, 0x02, 0x0a, 0x0c, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x66, 0x6c, 0x61, 0x67, 0x12, 0x38, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x56, 0x65,
	0x72, 0x64, 0x69, 0x63, 0x74, 0x52, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6c, 0x61, 0x67,
	0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x66,
	0x6c, 0x61, 0x67, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x6f, 0x0a, 0x07, 0x56, 0x65, 0x72,
	0x64, 0x69, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x13, 0x56, 0x45, 0x52, 0x44, 0x49, 0x43, 0x54, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a,
	0x10, 0x56, 0x45, 0x52, 0x44, 0x49, 0x43, 0x54, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x56, 0x45, 0x52, 0x44, 0x49, 0x43, 0x54, 0x5f, 0x4f,
	0x57, 0x4e, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x56, 0x45, 0x52, 0x44, 0x49, 0x43, 0x54, 0x5f,
	0x4f, 0x4c, 0x44, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x56, 0x45, 0x52, 0x44, 0x49, 0x43, 0x54,
	0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x04, 0x22, 0x4b, 0x0a, 0x13, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x34, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x2e,
	0x46, 0x6c, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x42, 0x6d, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x42, 0x0d, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0xa2, 0x02, 0x03, 0x52, 0x58, 0x58, 0xaa, 0x02,
	0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0xca, 0x02, 0x08, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0xe2, 0x02, 0x14, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x52, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_receiver_receiver_proto_rawDescOnce sync.Once
	file_receiver_receiver_proto_rawDescData = file_receiver_receiver_proto_rawDesc
)

func file_receiver_receiver_proto_rawDescGZIP() []byte {
	file_receiver_receiver_proto_rawDescOnce.Do(func() {
		file_receiver_receiver_proto_rawDescData = protoimpl.X.CompressGZIP(file_receiver_receiver_proto_rawDescData)
	})
	return file_receiver_receiver_proto_rawDescData
}

var file_receiver_receiver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_receiver_receiver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_receiver_receiver_proto_goTypes = []interface{}{
	(FlagResponse_Verdict)(0),   // 0: receiver.FlagResponse.Verdict
	(*SubmitFlagsRequest)(nil),  // 1: receiver.SubmitFlagsRequest
	(*FlagResponse)(nil),        // 2: receiver.FlagResponse
	(*SubmitFlagsResponse)(nil), // 3: receiver.SubmitFlagsResponse
}
var file_receiver_receiver_proto_depIdxs = []int32{
	0, // 0: receiver.FlagResponse.verdict:type_name -> receiver.FlagResponse.Verdict
	2, // 1: receiver.SubmitFlagsResponse.responses:type_name -> receiver.FlagResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_receiver_receiver_proto_init() }
func file_receiver_receiver_proto_init() {
	if File_receiver_receiver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_receiver_receiver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitFlagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receiver_receiver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_receiver_receiver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitFlagsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_receiver_receiver_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_receiver_receiver_proto_goTypes,
		DependencyIndexes: file_receiver_receiver_proto_depIdxs,
		EnumInfos:         file_receiver_receiver_proto_enumTypes,
		MessageInfos:      file_receiver_receiver_proto_msgTypes,
	}.Build()
	File_receiver_receiver_proto = out.File
	file_receiver_receiver_proto_rawDesc = nil
	file_receiver_receiver_proto_goTypes = nil
	file_receiver_receiver_proto_depIdxs = nil
}
