// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: receiver/receiver.proto

package receiver

import (
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *SubmitFlagsRequest) CloneVT() *SubmitFlagsRequest {
	if m == nil {
		return (*SubmitFlagsRequest)(nil)
	}
	r := new(SubmitFlagsRequest)
	if rhs := m.Flags; rhs != nil {
		tmpContainer := make([]string, len(rhs))
		copy(tmpContainer, rhs)
		r.Flags = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *SubmitFlagsRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *FlagResponse) CloneVT() *FlagResponse {
	if m == nil {
		return (*FlagResponse)(nil)
	}
	r := new(FlagResponse)
	r.Flag = m.Flag
	r.Verdict = m.Verdict
	r.Message = m.Message
	r.VictimId = m.VictimId
	r.ServiceId = m.ServiceId
	r.AttackerDelta = m.AttackerDelta
	r.VictimDelta = m.VictimDelta
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *FlagResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *AttackNotification_Batch) CloneVT() *AttackNotification_Batch {
	if m == nil {
		return (*AttackNotification_Batch)(nil)
	}
	r := new(AttackNotification_Batch)
	if rhs := m.Attacks; rhs != nil {
		tmpContainer := make([]*AttackNotification, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Attacks = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *AttackNotification_Batch) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *AttackNotification) CloneVT() *AttackNotification {
	if m == nil {
		return (*AttackNotification)(nil)
	}
	r := new(AttackNotification)
	r.AttackerId = m.AttackerId
	r.VictimId = m.VictimId
	r.ServiceId = m.ServiceId
	r.AttackerDelta = m.AttackerDelta
	r.VictimDelta = m.VictimDelta
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *AttackNotification) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *State_TeamService) CloneVT() *State_TeamService {
	if m == nil {
		return (*State_TeamService)(nil)
	}
	r := new(State_TeamService)
	r.TeamId = m.TeamId
	r.ServiceId = m.ServiceId
	r.Points = m.Points
	r.FlagsStolen = m.FlagsStolen
	r.FlagsLost = m.FlagsLost
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *State_TeamService) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *State) CloneVT() *State {
	if m == nil {
		return (*State)(nil)
	}
	r := new(State)
	if rhs := m.TeamServices; rhs != nil {
		tmpContainer := make([]*State_TeamService, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.TeamServices = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *State) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *SubmitFlagsResponse) CloneVT() *SubmitFlagsResponse {
	if m == nil {
		return (*SubmitFlagsResponse)(nil)
	}
	r := new(SubmitFlagsResponse)
	if rhs := m.Responses; rhs != nil {
		tmpContainer := make([]*FlagResponse, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Responses = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *SubmitFlagsResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *GetStateRequest) CloneVT() *GetStateRequest {
	if m == nil {
		return (*GetStateRequest)(nil)
	}
	r := new(GetStateRequest)
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *GetStateRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *GetStateResponse) CloneVT() *GetStateResponse {
	if m == nil {
		return (*GetStateResponse)(nil)
	}
	r := new(GetStateResponse)
	r.State = m.State.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *GetStateResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}
