// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: data/game_state/game_state_service.proto

package game_state

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GameStateService_Get_FullMethodName = "/data.game_state.GameStateService/Get"
)

// GameStateServiceClient is the client API for GameStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameStateServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type gameStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameStateServiceClient(cc grpc.ClientConnInterface) GameStateServiceClient {
	return &gameStateServiceClient{cc}
}

func (c *gameStateServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, GameStateService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameStateServiceServer is the server API for GameStateService service.
// All implementations must embed UnimplementedGameStateServiceServer
// for forward compatibility
type GameStateServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedGameStateServiceServer()
}

// UnimplementedGameStateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameStateServiceServer struct {
}

func (UnimplementedGameStateServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGameStateServiceServer) mustEmbedUnimplementedGameStateServiceServer() {}

// UnsafeGameStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameStateServiceServer will
// result in compilation errors.
type UnsafeGameStateServiceServer interface {
	mustEmbedUnimplementedGameStateServiceServer()
}

func RegisterGameStateServiceServer(s grpc.ServiceRegistrar, srv GameStateServiceServer) {
	s.RegisterService(&GameStateService_ServiceDesc, srv)
}

func _GameStateService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameStateServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameStateService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameStateServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameStateService_ServiceDesc is the grpc.ServiceDesc for GameStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.game_state.GameStateService",
	HandlerType: (*GameStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GameStateService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data/game_state/game_state_service.proto",
}
