// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/game_state/game_state.proto

package game_state

import (
	version "github.com/c4t-but-s4d/fastad/pkg/proto/data/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameStatus int32

const (
	GameStatus_GAME_STATUS_UNSPECIFIED GameStatus = 0
	GameStatus_GAME_STATUS_NOT_STARTED GameStatus = 1
	GameStatus_GAME_STATUS_RUNNING     GameStatus = 2
	GameStatus_GAME_STATUS_PAUSED      GameStatus = 3
	GameStatus_GAME_STATUS_FINISHED    GameStatus = 4
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "GAME_STATUS_UNSPECIFIED",
		1: "GAME_STATUS_NOT_STARTED",
		2: "GAME_STATUS_RUNNING",
		3: "GAME_STATUS_PAUSED",
		4: "GAME_STATUS_FINISHED",
	}
	GameStatus_value = map[string]int32{
		"GAME_STATUS_UNSPECIFIED": 0,
		"GAME_STATUS_NOT_STARTED": 1,
		"GAME_STATUS_RUNNING":     2,
		"GAME_STATUS_PAUSED":      3,
		"GAME_STATUS_FINISHED":    4,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_data_game_state_game_state_proto_enumTypes[0].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_data_game_state_game_state_proto_enumTypes[0]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{0}
}

type GameState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StartTime          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalRounds        uint64                 `protobuf:"varint,3,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`
	Status             GameStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=data.game_state.GameStatus" json:"status,omitempty"`
	FlagLifetimeRounds uint64                 `protobuf:"varint,5,opt,name=flag_lifetime_rounds,json=flagLifetimeRounds,proto3" json:"flag_lifetime_rounds,omitempty"`
	RoundDuration      *durationpb.Duration   `protobuf:"bytes,6,opt,name=round_duration,json=roundDuration,proto3" json:"round_duration,omitempty"`
	RunningRound       uint64                 `protobuf:"varint,7,opt,name=running_round,json=runningRound,proto3" json:"running_round,omitempty"`
	RunningRoundStart  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=running_round_start,json=runningRoundStart,proto3" json:"running_round_start,omitempty"`
	Hardness           float64                `protobuf:"fixed64,9,opt,name=hardness,proto3" json:"hardness,omitempty"`
	Inflation          bool                   `protobuf:"varint,10,opt,name=inflation,proto3" json:"inflation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_data_game_state_game_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{0}
}

func (x *GameState) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GameState) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GameState) GetTotalRounds() uint64 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *GameState) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

func (x *GameState) GetFlagLifetimeRounds() uint64 {
	if x != nil {
		return x.FlagLifetimeRounds
	}
	return 0
}

func (x *GameState) GetRoundDuration() *durationpb.Duration {
	if x != nil {
		return x.RoundDuration
	}
	return nil
}

func (x *GameState) GetRunningRound() uint64 {
	if x != nil {
		return x.RunningRound
	}
	return 0
}

func (x *GameState) GetRunningRoundStart() *timestamppb.Timestamp {
	if x != nil {
		return x.RunningRoundStart
	}
	return nil
}

func (x *GameState) GetHardness() float64 {
	if x != nil {
		return x.Hardness
	}
	return 0
}

func (x *GameState) GetInflation() bool {
	if x != nil {
		return x.Inflation
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *version.Version       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_data_game_state_game_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *GameState             `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	Version       *version.Version       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_data_game_state_game_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *GetResponse) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type UpdateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Zero time means no end time.
	EndTime            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalRounds        *uint64                `protobuf:"varint,3,opt,name=total_rounds,json=totalRounds,proto3,oneof" json:"total_rounds,omitempty"`
	Status             GameStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=data.game_state.GameStatus" json:"status,omitempty"`
	FlagLifetimeRounds *uint64                `protobuf:"varint,5,opt,name=flag_lifetime_rounds,json=flagLifetimeRounds,proto3,oneof" json:"flag_lifetime_rounds,omitempty"`
	RoundDuration      *durationpb.Duration   `protobuf:"bytes,6,opt,name=round_duration,json=roundDuration,proto3" json:"round_duration,omitempty"`
	Hardness           *float64               `protobuf:"fixed64,7,opt,name=hardness,proto3,oneof" json:"hardness,omitempty"`
	Inflation          *bool                  `protobuf:"varint,8,opt,name=inflation,proto3,oneof" json:"inflation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_data_game_state_game_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *UpdateRequest) GetTotalRounds() uint64 {
	if x != nil && x.TotalRounds != nil {
		return *x.TotalRounds
	}
	return 0
}

func (x *UpdateRequest) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

func (x *UpdateRequest) GetFlagLifetimeRounds() uint64 {
	if x != nil && x.FlagLifetimeRounds != nil {
		return *x.FlagLifetimeRounds
	}
	return 0
}

func (x *UpdateRequest) GetRoundDuration() *durationpb.Duration {
	if x != nil {
		return x.RoundDuration
	}
	return nil
}

func (x *UpdateRequest) GetHardness() float64 {
	if x != nil && x.Hardness != nil {
		return *x.Hardness
	}
	return 0
}

func (x *UpdateRequest) GetInflation() bool {
	if x != nil && x.Inflation != nil {
		return *x.Inflation
	}
	return false
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *GameState             `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	Version       *version.Version       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_data_game_state_game_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResponse) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *UpdateResponse) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type UpdateRoundRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RunningRound      uint64                 `protobuf:"varint,1,opt,name=running_round,json=runningRound,proto3" json:"running_round,omitempty"`
	RunningRoundStart *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=running_round_start,json=runningRoundStart,proto3" json:"running_round_start,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateRoundRequest) Reset() {
	*x = UpdateRoundRequest{}
	mi := &file_data_game_state_game_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoundRequest) ProtoMessage() {}

func (x *UpdateRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoundRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoundRequest) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoundRequest) GetRunningRound() uint64 {
	if x != nil {
		return x.RunningRound
	}
	return 0
}

func (x *UpdateRoundRequest) GetRunningRoundStart() *timestamppb.Timestamp {
	if x != nil {
		return x.RunningRoundStart
	}
	return nil
}

type UpdateRoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *GameState             `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	Version       *version.Version       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoundResponse) Reset() {
	*x = UpdateRoundResponse{}
	mi := &file_data_game_state_game_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoundResponse) ProtoMessage() {}

func (x *UpdateRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoundResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoundResponse) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoundResponse) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *UpdateRoundResponse) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type FinishGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishGameRequest) Reset() {
	*x = FinishGameRequest{}
	mi := &file_data_game_state_game_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishGameRequest) ProtoMessage() {}

func (x *FinishGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishGameRequest.ProtoReflect.Descriptor instead.
func (*FinishGameRequest) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{7}
}

type FinishGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *GameState             `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	Version       *version.Version       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishGameResponse) Reset() {
	*x = FinishGameResponse{}
	mi := &file_data_game_state_game_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishGameResponse) ProtoMessage() {}

func (x *FinishGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishGameResponse.ProtoReflect.Descriptor instead.
func (*FinishGameResponse) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{8}
}

func (x *FinishGameResponse) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *FinishGameResponse) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *GameState             `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_data_game_state_game_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRequest) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *GameState             `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	Version       *version.Version       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_data_game_state_game_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_game_state_game_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_data_game_state_game_state_proto_rawDescGZIP(), []int{10}
}

func (x *CreateResponse) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *CreateResponse) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

var File_data_game_state_game_state_proto protoreflect.FileDescriptor

const file_data_game_state_game_state_proto_rawDesc = "" +
	"\n" +
	" data/game_state/game_state.proto\x12\x0fdata.game_state\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1adata/version/version.proto\"\xf4\x03\n" +
	"\tGameState\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12!\n" +
	"\ftotal_rounds\x18\x03 \x01(\x04R\vtotalRounds\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.data.game_state.GameStatusR\x06status\x120\n" +
	"\x14flag_lifetime_rounds\x18\x05 \x01(\x04R\x12flagLifetimeRounds\x12@\n" +
	"\x0eround_duration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\rroundDuration\x12#\n" +
	"\rrunning_round\x18\a \x01(\x04R\frunningRound\x12J\n" +
	"\x13running_round_start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11runningRoundStart\x12\x1a\n" +
	"\bhardness\x18\t \x01(\x01R\bhardness\x12\x1c\n" +
	"\tinflation\x18\n" +
	" \x01(\bR\tinflation\"=\n" +
	"\n" +
	"GetRequest\x12/\n" +
	"\aversion\x18\x01 \x01(\v2\x15.data.version.VersionR\aversion\"y\n" +
	"\vGetResponse\x129\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x1a.data.game_state.GameStateR\tgameState\x12/\n" +
	"\aversion\x18\x02 \x01(\v2\x15.data.version.VersionR\aversion\"\xe0\x03\n" +
	"\rUpdateRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12&\n" +
	"\ftotal_rounds\x18\x03 \x01(\x04H\x00R\vtotalRounds\x88\x01\x01\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.data.game_state.GameStatusR\x06status\x125\n" +
	"\x14flag_lifetime_rounds\x18\x05 \x01(\x04H\x01R\x12flagLifetimeRounds\x88\x01\x01\x12@\n" +
	"\x0eround_duration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\rroundDuration\x12\x1f\n" +
	"\bhardness\x18\a \x01(\x01H\x02R\bhardness\x88\x01\x01\x12!\n" +
	"\tinflation\x18\b \x01(\bH\x03R\tinflation\x88\x01\x01B\x0f\n" +
	"\r_total_roundsB\x17\n" +
	"\x15_flag_lifetime_roundsB\v\n" +
	"\t_hardnessB\f\n" +
	"\n" +
	"_inflation\"|\n" +
	"\x0eUpdateResponse\x129\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x1a.data.game_state.GameStateR\tgameState\x12/\n" +
	"\aversion\x18\x02 \x01(\v2\x15.data.version.VersionR\aversion\"\x85\x01\n" +
	"\x12UpdateRoundRequest\x12#\n" +
	"\rrunning_round\x18\x01 \x01(\x04R\frunningRound\x12J\n" +
	"\x13running_round_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x11runningRoundStart\"\x81\x01\n" +
	"\x13UpdateRoundResponse\x129\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x1a.data.game_state.GameStateR\tgameState\x12/\n" +
	"\aversion\x18\x02 \x01(\v2\x15.data.version.VersionR\aversion\"\x13\n" +
	"\x11FinishGameRequest\"\x80\x01\n" +
	"\x12FinishGameResponse\x129\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x1a.data.game_state.GameStateR\tgameState\x12/\n" +
	"\aversion\x18\x02 \x01(\v2\x15.data.version.VersionR\aversion\"J\n" +
	"\rCreateRequest\x129\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x1a.data.game_state.GameStateR\tgameState\"|\n" +
	"\x0eCreateResponse\x129\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x1a.data.game_state.GameStateR\tgameState\x12/\n" +
	"\aversion\x18\x02 \x01(\v2\x15.data.version.VersionR\aversion*\x91\x01\n" +
	"\n" +
	"GameStatus\x12\x1b\n" +
	"\x17GAME_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17GAME_STATUS_NOT_STARTED\x10\x01\x12\x17\n" +
	"\x13GAME_STATUS_RUNNING\x10\x02\x12\x16\n" +
	"\x12GAME_STATUS_PAUSED\x10\x03\x12\x18\n" +
	"\x14GAME_STATUS_FINISHED\x10\x04B\xb7\x01\n" +
	"\x13com.data.game_stateB\x0eGameStateProtoP\x01Z7github.com/c4t-but-s4d/fastad/pkg/proto/data/game_state\xa2\x02\x03DGX\xaa\x02\x0eData.GameState\xca\x02\x0eData\\GameState\xe2\x02\x1aData\\GameState\\GPBMetadata\xea\x02\x0fData::GameStateb\x06proto3"

var (
	file_data_game_state_game_state_proto_rawDescOnce sync.Once
	file_data_game_state_game_state_proto_rawDescData []byte
)

func file_data_game_state_game_state_proto_rawDescGZIP() []byte {
	file_data_game_state_game_state_proto_rawDescOnce.Do(func() {
		file_data_game_state_game_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_game_state_game_state_proto_rawDesc), len(file_data_game_state_game_state_proto_rawDesc)))
	})
	return file_data_game_state_game_state_proto_rawDescData
}

var file_data_game_state_game_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_game_state_game_state_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_data_game_state_game_state_proto_goTypes = []any{
	(GameStatus)(0),               // 0: data.game_state.GameStatus
	(*GameState)(nil),             // 1: data.game_state.GameState
	(*GetRequest)(nil),            // 2: data.game_state.GetRequest
	(*GetResponse)(nil),           // 3: data.game_state.GetResponse
	(*UpdateRequest)(nil),         // 4: data.game_state.UpdateRequest
	(*UpdateResponse)(nil),        // 5: data.game_state.UpdateResponse
	(*UpdateRoundRequest)(nil),    // 6: data.game_state.UpdateRoundRequest
	(*UpdateRoundResponse)(nil),   // 7: data.game_state.UpdateRoundResponse
	(*FinishGameRequest)(nil),     // 8: data.game_state.FinishGameRequest
	(*FinishGameResponse)(nil),    // 9: data.game_state.FinishGameResponse
	(*CreateRequest)(nil),         // 10: data.game_state.CreateRequest
	(*CreateResponse)(nil),        // 11: data.game_state.CreateResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
	(*version.Version)(nil),       // 14: data.version.Version
}
var file_data_game_state_game_state_proto_depIdxs = []int32{
	12, // 0: data.game_state.GameState.start_time:type_name -> google.protobuf.Timestamp
	12, // 1: data.game_state.GameState.end_time:type_name -> google.protobuf.Timestamp
	0,  // 2: data.game_state.GameState.status:type_name -> data.game_state.GameStatus
	13, // 3: data.game_state.GameState.round_duration:type_name -> google.protobuf.Duration
	12, // 4: data.game_state.GameState.running_round_start:type_name -> google.protobuf.Timestamp
	14, // 5: data.game_state.GetRequest.version:type_name -> data.version.Version
	1,  // 6: data.game_state.GetResponse.game_state:type_name -> data.game_state.GameState
	14, // 7: data.game_state.GetResponse.version:type_name -> data.version.Version
	12, // 8: data.game_state.UpdateRequest.start_time:type_name -> google.protobuf.Timestamp
	12, // 9: data.game_state.UpdateRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 10: data.game_state.UpdateRequest.status:type_name -> data.game_state.GameStatus
	13, // 11: data.game_state.UpdateRequest.round_duration:type_name -> google.protobuf.Duration
	1,  // 12: data.game_state.UpdateResponse.game_state:type_name -> data.game_state.GameState
	14, // 13: data.game_state.UpdateResponse.version:type_name -> data.version.Version
	12, // 14: data.game_state.UpdateRoundRequest.running_round_start:type_name -> google.protobuf.Timestamp
	1,  // 15: data.game_state.UpdateRoundResponse.game_state:type_name -> data.game_state.GameState
	14, // 16: data.game_state.UpdateRoundResponse.version:type_name -> data.version.Version
	1,  // 17: data.game_state.FinishGameResponse.game_state:type_name -> data.game_state.GameState
	14, // 18: data.game_state.FinishGameResponse.version:type_name -> data.version.Version
	1,  // 19: data.game_state.CreateRequest.game_state:type_name -> data.game_state.GameState
	1,  // 20: data.game_state.CreateResponse.game_state:type_name -> data.game_state.GameState
	14, // 21: data.game_state.CreateResponse.version:type_name -> data.version.Version
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_data_game_state_game_state_proto_init() }
func file_data_game_state_game_state_proto_init() {
	if File_data_game_state_game_state_proto != nil {
		return
	}
	file_data_game_state_game_state_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_game_state_game_state_proto_rawDesc), len(file_data_game_state_game_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_game_state_game_state_proto_goTypes,
		DependencyIndexes: file_data_game_state_game_state_proto_depIdxs,
		EnumInfos:         file_data_game_state_game_state_proto_enumTypes,
		MessageInfos:      file_data_game_state_game_state_proto_msgTypes,
	}.Build()
	File_data_game_state_game_state_proto = out.File
	file_data_game_state_game_state_proto_goTypes = nil
	file_data_game_state_game_state_proto_depIdxs = nil
}
