// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: data/game_state/game_state.proto

package game_state

import (
	durationpb1 "github.com/planetscale/vtprotobuf/types/known/durationpb"
	timestamppb1 "github.com/planetscale/vtprotobuf/types/known/timestamppb"
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *GameState) CloneVT() *GameState {
	if m == nil {
		return (*GameState)(nil)
	}
	r := new(GameState)
	r.StartTime = (*timestamppb.Timestamp)((*timestamppb1.Timestamp)(m.StartTime).CloneVT())
	r.EndTime = (*timestamppb.Timestamp)((*timestamppb1.Timestamp)(m.EndTime).CloneVT())
	r.TotalRounds = m.TotalRounds
	r.Paused = m.Paused
	r.Finished = m.Finished
	r.FlagLifetimeRounds = m.FlagLifetimeRounds
	r.RoundDuration = (*durationpb.Duration)((*durationpb1.Duration)(m.RoundDuration).CloneVT())
	r.Mode = m.Mode
	r.RunningRound = m.RunningRound
	r.RunningRoundStart = (*timestamppb.Timestamp)((*timestamppb1.Timestamp)(m.RunningRoundStart).CloneVT())
	r.Hardness = m.Hardness
	r.Inflation = m.Inflation
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *GameState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *GetRequest) CloneVT() *GetRequest {
	if m == nil {
		return (*GetRequest)(nil)
	}
	r := new(GetRequest)
	r.Version = m.Version.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *GetRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *GetResponse) CloneVT() *GetResponse {
	if m == nil {
		return (*GetResponse)(nil)
	}
	r := new(GetResponse)
	r.GameState = m.GameState.CloneVT()
	r.Version = m.Version.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *GetResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *UpdateRequest) CloneVT() *UpdateRequest {
	if m == nil {
		return (*UpdateRequest)(nil)
	}
	r := new(UpdateRequest)
	r.StartTime = (*timestamppb.Timestamp)((*timestamppb1.Timestamp)(m.StartTime).CloneVT())
	r.EndTime = (*timestamppb.Timestamp)((*timestamppb1.Timestamp)(m.EndTime).CloneVT())
	r.TotalRounds = m.TotalRounds
	r.Paused = m.Paused
	r.FlagLifetimeRounds = m.FlagLifetimeRounds
	r.RoundDuration = (*durationpb.Duration)((*durationpb1.Duration)(m.RoundDuration).CloneVT())
	r.Mode = m.Mode
	r.Hardness = m.Hardness
	r.Inflation = m.Inflation
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *UpdateRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *UpdateResponse) CloneVT() *UpdateResponse {
	if m == nil {
		return (*UpdateResponse)(nil)
	}
	r := new(UpdateResponse)
	r.GameState = m.GameState.CloneVT()
	r.Version = m.Version.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *UpdateResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *UpdateRoundRequest) CloneVT() *UpdateRoundRequest {
	if m == nil {
		return (*UpdateRoundRequest)(nil)
	}
	r := new(UpdateRoundRequest)
	r.RunningRound = m.RunningRound
	r.RunningRoundStart = (*timestamppb.Timestamp)((*timestamppb1.Timestamp)(m.RunningRoundStart).CloneVT())
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *UpdateRoundRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *UpdateRoundResponse) CloneVT() *UpdateRoundResponse {
	if m == nil {
		return (*UpdateRoundResponse)(nil)
	}
	r := new(UpdateRoundResponse)
	r.GameState = m.GameState.CloneVT()
	r.Version = m.Version.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *UpdateRoundResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *FinishGameRequest) CloneVT() *FinishGameRequest {
	if m == nil {
		return (*FinishGameRequest)(nil)
	}
	r := new(FinishGameRequest)
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *FinishGameRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *FinishGameResponse) CloneVT() *FinishGameResponse {
	if m == nil {
		return (*FinishGameResponse)(nil)
	}
	r := new(FinishGameResponse)
	r.GameState = m.GameState.CloneVT()
	r.Version = m.Version.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *FinishGameResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (this *GameState) EqualVT(that *GameState) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !(*timestamppb1.Timestamp)(this.StartTime).EqualVT((*timestamppb1.Timestamp)(that.StartTime)) {
		return false
	}
	if !(*timestamppb1.Timestamp)(this.EndTime).EqualVT((*timestamppb1.Timestamp)(that.EndTime)) {
		return false
	}
	if this.TotalRounds != that.TotalRounds {
		return false
	}
	if this.Paused != that.Paused {
		return false
	}
	if this.FlagLifetimeRounds != that.FlagLifetimeRounds {
		return false
	}
	if !(*durationpb1.Duration)(this.RoundDuration).EqualVT((*durationpb1.Duration)(that.RoundDuration)) {
		return false
	}
	if this.Mode != that.Mode {
		return false
	}
	if this.RunningRound != that.RunningRound {
		return false
	}
	if !(*timestamppb1.Timestamp)(this.RunningRoundStart).EqualVT((*timestamppb1.Timestamp)(that.RunningRoundStart)) {
		return false
	}
	if this.Hardness != that.Hardness {
		return false
	}
	if this.Inflation != that.Inflation {
		return false
	}
	if this.Finished != that.Finished {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *GameState) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*GameState)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *GetRequest) EqualVT(that *GetRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.Version.EqualVT(that.Version) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *GetRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*GetRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *GetResponse) EqualVT(that *GetResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.GameState.EqualVT(that.GameState) {
		return false
	}
	if !this.Version.EqualVT(that.Version) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *GetResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*GetResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *UpdateRequest) EqualVT(that *UpdateRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !(*timestamppb1.Timestamp)(this.StartTime).EqualVT((*timestamppb1.Timestamp)(that.StartTime)) {
		return false
	}
	if !(*timestamppb1.Timestamp)(this.EndTime).EqualVT((*timestamppb1.Timestamp)(that.EndTime)) {
		return false
	}
	if this.TotalRounds != that.TotalRounds {
		return false
	}
	if this.Paused != that.Paused {
		return false
	}
	if this.FlagLifetimeRounds != that.FlagLifetimeRounds {
		return false
	}
	if !(*durationpb1.Duration)(this.RoundDuration).EqualVT((*durationpb1.Duration)(that.RoundDuration)) {
		return false
	}
	if this.Mode != that.Mode {
		return false
	}
	if this.Hardness != that.Hardness {
		return false
	}
	if this.Inflation != that.Inflation {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *UpdateRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*UpdateRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *UpdateResponse) EqualVT(that *UpdateResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.GameState.EqualVT(that.GameState) {
		return false
	}
	if !this.Version.EqualVT(that.Version) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *UpdateResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*UpdateResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *UpdateRoundRequest) EqualVT(that *UpdateRoundRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.RunningRound != that.RunningRound {
		return false
	}
	if !(*timestamppb1.Timestamp)(this.RunningRoundStart).EqualVT((*timestamppb1.Timestamp)(that.RunningRoundStart)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *UpdateRoundRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*UpdateRoundRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *UpdateRoundResponse) EqualVT(that *UpdateRoundResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.GameState.EqualVT(that.GameState) {
		return false
	}
	if !this.Version.EqualVT(that.Version) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *UpdateRoundResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*UpdateRoundResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *FinishGameRequest) EqualVT(that *FinishGameRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *FinishGameRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*FinishGameRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *FinishGameResponse) EqualVT(that *FinishGameResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.GameState.EqualVT(that.GameState) {
		return false
	}
	if !this.Version.EqualVT(that.Version) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *FinishGameResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*FinishGameResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
