// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: checker/checker.proto

package checker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ACTION_CHECK       Action = 1
	Action_ACTION_PUT         Action = 2
	Action_ACTION_GET         Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_CHECK",
		2: "ACTION_PUT",
		3: "ACTION_GET",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_CHECK":       1,
		"ACTION_PUT":         2,
		"ACTION_GET":         3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_checker_checker_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_checker_checker_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_checker_checker_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED  Status = 0
	Status_STATUS_UP           Status = 1
	Status_STATUS_MUMBLE       Status = 2
	Status_STATUS_CORRUPT      Status = 3
	Status_STATUS_DOWN         Status = 4
	Status_STATUS_CHECK_FAILED Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_UP",
		2: "STATUS_MUMBLE",
		3: "STATUS_CORRUPT",
		4: "STATUS_DOWN",
		5: "STATUS_CHECK_FAILED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":  0,
		"STATUS_UP":           1,
		"STATUS_MUMBLE":       2,
		"STATUS_CORRUPT":      3,
		"STATUS_DOWN":         4,
		"STATUS_CHECK_FAILED": 5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_checker_checker_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_checker_checker_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_checker_checker_proto_rawDescGZIP(), []int{1}
}

type Type int32

const (
	Type_TYPE_UNSPECIFIED Type = 0
	Type_TYPE_LEGACY      Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_LEGACY",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_LEGACY":      1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_checker_checker_proto_enumTypes[2].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_checker_checker_proto_enumTypes[2]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_checker_checker_proto_rawDescGZIP(), []int{2}
}

type Execution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ServiceId     int64                  `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Action        Action                 `protobuf:"varint,3,opt,name=action,proto3,enum=checker.Action" json:"action,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=checker.Status" json:"status,omitempty"`
	Public        string                 `protobuf:"bytes,5,opt,name=public,proto3" json:"public,omitempty"`
	Private       string                 `protobuf:"bytes,6,opt,name=private,proto3" json:"private,omitempty"`
	Command       string                 `protobuf:"bytes,7,opt,name=command,proto3" json:"command,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Execution) Reset() {
	*x = Execution{}
	mi := &file_checker_checker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution) ProtoMessage() {}

func (x *Execution) ProtoReflect() protoreflect.Message {
	mi := &file_checker_checker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution.ProtoReflect.Descriptor instead.
func (*Execution) Descriptor() ([]byte, []int) {
	return file_checker_checker_proto_rawDescGZIP(), []int{0}
}

func (x *Execution) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *Execution) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *Execution) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNSPECIFIED
}

func (x *Execution) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Execution) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

func (x *Execution) GetPrivate() string {
	if x != nil {
		return x.Private
	}
	return ""
}

func (x *Execution) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Execution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Execution_Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*Execution           `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Execution_Batch) Reset() {
	*x = Execution_Batch{}
	mi := &file_checker_checker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution_Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution_Batch) ProtoMessage() {}

func (x *Execution_Batch) ProtoReflect() protoreflect.Message {
	mi := &file_checker_checker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution_Batch.ProtoReflect.Descriptor instead.
func (*Execution_Batch) Descriptor() ([]byte, []int) {
	return file_checker_checker_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Execution_Batch) GetExecutions() []*Execution {
	if x != nil {
		return x.Executions
	}
	return nil
}

var File_checker_checker_proto protoreflect.FileDescriptor

const file_checker_checker_proto_rawDesc = "" +
	"\n" +
	"\x15checker/checker.proto\x12\achecker\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x02\n" +
	"\tExecution\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x03R\tserviceId\x12'\n" +
	"\x06action\x18\x03 \x01(\x0e2\x0f.checker.ActionR\x06action\x12'\n" +
	"\x06status\x18\x04 \x01(\x0e2\x0f.checker.StatusR\x06status\x12\x16\n" +
	"\x06public\x18\x05 \x01(\tR\x06public\x12\x18\n" +
	"\aprivate\x18\x06 \x01(\tR\aprivate\x12\x18\n" +
	"\acommand\x18\a \x01(\tR\acommand\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\x05Batch\x122\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x12.checker.ExecutionR\n" +
	"executions*R\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_CHECK\x10\x01\x12\x0e\n" +
	"\n" +
	"ACTION_PUT\x10\x02\x12\x0e\n" +
	"\n" +
	"ACTION_GET\x10\x03*\x80\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_UP\x10\x01\x12\x11\n" +
	"\rSTATUS_MUMBLE\x10\x02\x12\x12\n" +
	"\x0eSTATUS_CORRUPT\x10\x03\x12\x0f\n" +
	"\vSTATUS_DOWN\x10\x04\x12\x17\n" +
	"\x13STATUS_CHECK_FAILED\x10\x05*-\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTYPE_LEGACY\x10\x01B\x88\x01\n" +
	"\vcom.checkerB\fCheckerProtoP\x01Z/github.com/c4t-but-s4d/fastad/pkg/proto/checker\xa2\x02\x03CXX\xaa\x02\aChecker\xca\x02\aChecker\xe2\x02\x13Checker\\GPBMetadata\xea\x02\aCheckerb\x06proto3"

var (
	file_checker_checker_proto_rawDescOnce sync.Once
	file_checker_checker_proto_rawDescData []byte
)

func file_checker_checker_proto_rawDescGZIP() []byte {
	file_checker_checker_proto_rawDescOnce.Do(func() {
		file_checker_checker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_checker_checker_proto_rawDesc), len(file_checker_checker_proto_rawDesc)))
	})
	return file_checker_checker_proto_rawDescData
}

var file_checker_checker_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_checker_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_checker_checker_proto_goTypes = []any{
	(Action)(0),                   // 0: checker.Action
	(Status)(0),                   // 1: checker.Status
	(Type)(0),                     // 2: checker.Type
	(*Execution)(nil),             // 3: checker.Execution
	(*Execution_Batch)(nil),       // 4: checker.Execution.Batch
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_checker_checker_proto_depIdxs = []int32{
	0, // 0: checker.Execution.action:type_name -> checker.Action
	1, // 1: checker.Execution.status:type_name -> checker.Status
	5, // 2: checker.Execution.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: checker.Execution.Batch.executions:type_name -> checker.Execution
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_checker_checker_proto_init() }
func file_checker_checker_proto_init() {
	if File_checker_checker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_checker_checker_proto_rawDesc), len(file_checker_checker_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_checker_checker_proto_goTypes,
		DependencyIndexes: file_checker_checker_proto_depIdxs,
		EnumInfos:         file_checker_checker_proto_enumTypes,
		MessageInfos:      file_checker_checker_proto_msgTypes,
	}.Build()
	File_checker_checker_proto = out.File
	file_checker_checker_proto_goTypes = nil
	file_checker_checker_proto_depIdxs = nil
}
