// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: checker/checker.proto

package checker

import (
	timestamppb1 "github.com/planetscale/vtprotobuf/types/known/timestamppb"
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *Execution_Batch) CloneVT() *Execution_Batch {
	if m == nil {
		return (*Execution_Batch)(nil)
	}
	r := new(Execution_Batch)
	if rhs := m.Executions; rhs != nil {
		tmpContainer := make([]*Execution, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Executions = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Execution_Batch) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *Execution) CloneVT() *Execution {
	if m == nil {
		return (*Execution)(nil)
	}
	r := new(Execution)
	r.TeamId = m.TeamId
	r.ServiceId = m.ServiceId
	r.Action = m.Action
	r.Status = m.Status
	r.Public = m.Public
	r.Private = m.Private
	r.Command = m.Command
	r.CreatedAt = (*timestamppb.Timestamp)((*timestamppb1.Timestamp)(m.CreatedAt).CloneVT())
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Execution) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (this *Execution_Batch) EqualVT(that *Execution_Batch) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Executions) != len(that.Executions) {
		return false
	}
	for i, vx := range this.Executions {
		vy := that.Executions[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Execution{}
			}
			if q == nil {
				q = &Execution{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Execution_Batch) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*Execution_Batch)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Execution) EqualVT(that *Execution) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.TeamId != that.TeamId {
		return false
	}
	if this.ServiceId != that.ServiceId {
		return false
	}
	if this.Action != that.Action {
		return false
	}
	if this.Status != that.Status {
		return false
	}
	if this.Public != that.Public {
		return false
	}
	if this.Private != that.Private {
		return false
	}
	if this.Command != that.Command {
		return false
	}
	if !(*timestamppb1.Timestamp)(this.CreatedAt).EqualVT((*timestamppb1.Timestamp)(that.CreatedAt)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Execution) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*Execution)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
