// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: scoreboard/scoreboard.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Status, statusFromJSON, statusToJSON } from "../checker/checker";

export const protobufPackage = "scoreboard";

export interface Scoreboard {
  teamServiceStates: Scoreboard_TeamServiceState[];
}

export interface Scoreboard_TeamServiceState {
  teamId: bigint;
  serviceId: bigint;
  /** From slac. */
  checksTotal: bigint;
  checksPassed: bigint;
  status: Status;
  /** From receiver. */
  points: number;
  flagsStolen: bigint;
  flagsLost: bigint;
}

function createBaseScoreboard(): Scoreboard {
  return { teamServiceStates: [] };
}

export const Scoreboard: MessageFns<Scoreboard> = {
  encode(message: Scoreboard, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.teamServiceStates) {
      Scoreboard_TeamServiceState.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Scoreboard {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScoreboard();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.teamServiceStates.push(Scoreboard_TeamServiceState.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  // encodeTransform encodes a source of message objects.
  // Transform<Scoreboard, Uint8Array>
  async *encodeTransform(
    source: AsyncIterable<Scoreboard | Scoreboard[]> | Iterable<Scoreboard | Scoreboard[]>,
  ): AsyncIterable<Uint8Array> {
    for await (const pkt of source) {
      if (globalThis.Array.isArray(pkt)) {
        for (const p of (pkt as any)) {
          yield* [Scoreboard.encode(p).finish()];
        }
      } else {
        yield* [Scoreboard.encode(pkt as any).finish()];
      }
    }
  },

  // decodeTransform decodes a source of encoded messages.
  // Transform<Uint8Array, Scoreboard>
  async *decodeTransform(
    source: AsyncIterable<Uint8Array | Uint8Array[]> | Iterable<Uint8Array | Uint8Array[]>,
  ): AsyncIterable<Scoreboard> {
    for await (const pkt of source) {
      if (globalThis.Array.isArray(pkt)) {
        for (const p of (pkt as any)) {
          yield* [Scoreboard.decode(p)];
        }
      } else {
        yield* [Scoreboard.decode(pkt as any)];
      }
    }
  },

  fromJSON(object: any): Scoreboard {
    return {
      teamServiceStates: globalThis.Array.isArray(object?.teamServiceStates)
        ? object.teamServiceStates.map((e: any) => Scoreboard_TeamServiceState.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Scoreboard): unknown {
    const obj: any = {};
    if (message.teamServiceStates?.length) {
      obj.teamServiceStates = message.teamServiceStates.map((e) => Scoreboard_TeamServiceState.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Scoreboard>, I>>(base?: I): Scoreboard {
    return Scoreboard.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Scoreboard>, I>>(object: I): Scoreboard {
    const message = createBaseScoreboard();
    message.teamServiceStates = object.teamServiceStates?.map((e) => Scoreboard_TeamServiceState.fromPartial(e)) || [];
    return message;
  },
};

function createBaseScoreboard_TeamServiceState(): Scoreboard_TeamServiceState {
  return {
    teamId: 0n,
    serviceId: 0n,
    checksTotal: 0n,
    checksPassed: 0n,
    status: 0,
    points: 0,
    flagsStolen: 0n,
    flagsLost: 0n,
  };
}

export const Scoreboard_TeamServiceState: MessageFns<Scoreboard_TeamServiceState> = {
  encode(message: Scoreboard_TeamServiceState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.teamId !== 0n) {
      if (BigInt.asIntN(64, message.teamId) !== message.teamId) {
        throw new globalThis.Error("value provided for field message.teamId of type int64 too large");
      }
      writer.uint32(8).int64(message.teamId);
    }
    if (message.serviceId !== 0n) {
      if (BigInt.asIntN(64, message.serviceId) !== message.serviceId) {
        throw new globalThis.Error("value provided for field message.serviceId of type int64 too large");
      }
      writer.uint32(16).int64(message.serviceId);
    }
    if (message.checksTotal !== 0n) {
      if (BigInt.asIntN(64, message.checksTotal) !== message.checksTotal) {
        throw new globalThis.Error("value provided for field message.checksTotal of type int64 too large");
      }
      writer.uint32(24).int64(message.checksTotal);
    }
    if (message.checksPassed !== 0n) {
      if (BigInt.asIntN(64, message.checksPassed) !== message.checksPassed) {
        throw new globalThis.Error("value provided for field message.checksPassed of type int64 too large");
      }
      writer.uint32(32).int64(message.checksPassed);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.points !== 0) {
      writer.uint32(49).double(message.points);
    }
    if (message.flagsStolen !== 0n) {
      if (BigInt.asIntN(64, message.flagsStolen) !== message.flagsStolen) {
        throw new globalThis.Error("value provided for field message.flagsStolen of type int64 too large");
      }
      writer.uint32(56).int64(message.flagsStolen);
    }
    if (message.flagsLost !== 0n) {
      if (BigInt.asIntN(64, message.flagsLost) !== message.flagsLost) {
        throw new globalThis.Error("value provided for field message.flagsLost of type int64 too large");
      }
      writer.uint32(64).int64(message.flagsLost);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Scoreboard_TeamServiceState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScoreboard_TeamServiceState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.teamId = reader.int64() as bigint;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.serviceId = reader.int64() as bigint;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.checksTotal = reader.int64() as bigint;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.checksPassed = reader.int64() as bigint;
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.points = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.flagsStolen = reader.int64() as bigint;
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.flagsLost = reader.int64() as bigint;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  // encodeTransform encodes a source of message objects.
  // Transform<Scoreboard_TeamServiceState, Uint8Array>
  async *encodeTransform(
    source:
      | AsyncIterable<Scoreboard_TeamServiceState | Scoreboard_TeamServiceState[]>
      | Iterable<Scoreboard_TeamServiceState | Scoreboard_TeamServiceState[]>,
  ): AsyncIterable<Uint8Array> {
    for await (const pkt of source) {
      if (globalThis.Array.isArray(pkt)) {
        for (const p of (pkt as any)) {
          yield* [Scoreboard_TeamServiceState.encode(p).finish()];
        }
      } else {
        yield* [Scoreboard_TeamServiceState.encode(pkt as any).finish()];
      }
    }
  },

  // decodeTransform decodes a source of encoded messages.
  // Transform<Uint8Array, Scoreboard_TeamServiceState>
  async *decodeTransform(
    source: AsyncIterable<Uint8Array | Uint8Array[]> | Iterable<Uint8Array | Uint8Array[]>,
  ): AsyncIterable<Scoreboard_TeamServiceState> {
    for await (const pkt of source) {
      if (globalThis.Array.isArray(pkt)) {
        for (const p of (pkt as any)) {
          yield* [Scoreboard_TeamServiceState.decode(p)];
        }
      } else {
        yield* [Scoreboard_TeamServiceState.decode(pkt as any)];
      }
    }
  },

  fromJSON(object: any): Scoreboard_TeamServiceState {
    return {
      teamId: isSet(object.teamId) ? BigInt(object.teamId) : 0n,
      serviceId: isSet(object.serviceId) ? BigInt(object.serviceId) : 0n,
      checksTotal: isSet(object.checksTotal) ? BigInt(object.checksTotal) : 0n,
      checksPassed: isSet(object.checksPassed) ? BigInt(object.checksPassed) : 0n,
      status: isSet(object.status) ? statusFromJSON(object.status) : 0,
      points: isSet(object.points) ? globalThis.Number(object.points) : 0,
      flagsStolen: isSet(object.flagsStolen) ? BigInt(object.flagsStolen) : 0n,
      flagsLost: isSet(object.flagsLost) ? BigInt(object.flagsLost) : 0n,
    };
  },

  toJSON(message: Scoreboard_TeamServiceState): unknown {
    const obj: any = {};
    if (message.teamId !== 0n) {
      obj.teamId = message.teamId.toString();
    }
    if (message.serviceId !== 0n) {
      obj.serviceId = message.serviceId.toString();
    }
    if (message.checksTotal !== 0n) {
      obj.checksTotal = message.checksTotal.toString();
    }
    if (message.checksPassed !== 0n) {
      obj.checksPassed = message.checksPassed.toString();
    }
    if (message.status !== 0) {
      obj.status = statusToJSON(message.status);
    }
    if (message.points !== 0) {
      obj.points = message.points;
    }
    if (message.flagsStolen !== 0n) {
      obj.flagsStolen = message.flagsStolen.toString();
    }
    if (message.flagsLost !== 0n) {
      obj.flagsLost = message.flagsLost.toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Scoreboard_TeamServiceState>, I>>(base?: I): Scoreboard_TeamServiceState {
    return Scoreboard_TeamServiceState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Scoreboard_TeamServiceState>, I>>(object: I): Scoreboard_TeamServiceState {
    const message = createBaseScoreboard_TeamServiceState();
    message.teamId = object.teamId ?? 0n;
    message.serviceId = object.serviceId ?? 0n;
    message.checksTotal = object.checksTotal ?? 0n;
    message.checksPassed = object.checksPassed ?? 0n;
    message.status = object.status ?? 0;
    message.points = object.points ?? 0;
    message.flagsStolen = object.flagsStolen ?? 0n;
    message.flagsLost = object.flagsLost ?? 0n;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  encodeTransform(source: AsyncIterable<T | T[]> | Iterable<T | T[]>): AsyncIterable<Uint8Array>;
  decodeTransform(
    source: AsyncIterable<Uint8Array | Uint8Array[]> | Iterable<Uint8Array | Uint8Array[]>,
  ): AsyncIterable<T>;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
