// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: scoreboard/scoreboard.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { TeamServiceState_CheckStatus } from "../slac/slac";

export const protobufPackage = "scoreboard";

export interface Scoreboard {
  teamServiceStates: Scoreboard_TeamServiceState[];
}

export interface Scoreboard_TeamServiceState {
  teamId: string;
  serviceId: string;
  /** From slac. */
  checksTotal: string;
  checksPassed: string;
  checkStatuses: TeamServiceState_CheckStatus[];
  /** From receiver. */
  points: number;
  flagsStolen: string;
  flagsLost: string;
}

function createBaseScoreboard(): Scoreboard {
  return { teamServiceStates: [] };
}

export const Scoreboard: MessageFns<Scoreboard> = {
  encode(message: Scoreboard, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.teamServiceStates) {
      Scoreboard_TeamServiceState.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Scoreboard {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScoreboard();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.teamServiceStates.push(Scoreboard_TeamServiceState.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  // encodeTransform encodes a source of message objects.
  // Transform<Scoreboard, Uint8Array>
  async *encodeTransform(
    source: AsyncIterable<Scoreboard | Scoreboard[]> | Iterable<Scoreboard | Scoreboard[]>,
  ): AsyncIterable<Uint8Array> {
    for await (const pkt of source) {
      if (globalThis.Array.isArray(pkt)) {
        for (const p of (pkt as any)) {
          yield* [Scoreboard.encode(p).finish()];
        }
      } else {
        yield* [Scoreboard.encode(pkt as any).finish()];
      }
    }
  },

  // decodeTransform decodes a source of encoded messages.
  // Transform<Uint8Array, Scoreboard>
  async *decodeTransform(
    source: AsyncIterable<Uint8Array | Uint8Array[]> | Iterable<Uint8Array | Uint8Array[]>,
  ): AsyncIterable<Scoreboard> {
    for await (const pkt of source) {
      if (globalThis.Array.isArray(pkt)) {
        for (const p of (pkt as any)) {
          yield* [Scoreboard.decode(p)];
        }
      } else {
        yield* [Scoreboard.decode(pkt as any)];
      }
    }
  },

  fromJSON(object: any): Scoreboard {
    return {
      teamServiceStates: globalThis.Array.isArray(object?.teamServiceStates)
        ? object.teamServiceStates.map((e: any) => Scoreboard_TeamServiceState.fromJSON(e))
        : globalThis.Array.isArray(object?.team_service_states)
        ? object.team_service_states.map((e: any) => Scoreboard_TeamServiceState.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Scoreboard): unknown {
    const obj: any = {};
    if (message.teamServiceStates?.length) {
      obj.teamServiceStates = message.teamServiceStates.map((e) => Scoreboard_TeamServiceState.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Scoreboard>, I>>(base?: I): Scoreboard {
    return Scoreboard.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Scoreboard>, I>>(object: I): Scoreboard {
    const message = createBaseScoreboard();
    message.teamServiceStates = object.teamServiceStates?.map((e) => Scoreboard_TeamServiceState.fromPartial(e)) || [];
    return message;
  },
};

function createBaseScoreboard_TeamServiceState(): Scoreboard_TeamServiceState {
  return {
    teamId: "0",
    serviceId: "0",
    checksTotal: "0",
    checksPassed: "0",
    checkStatuses: [],
    points: 0,
    flagsStolen: "0",
    flagsLost: "0",
  };
}

export const Scoreboard_TeamServiceState: MessageFns<Scoreboard_TeamServiceState> = {
  encode(message: Scoreboard_TeamServiceState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.teamId !== "0") {
      writer.uint32(8).int64(message.teamId);
    }
    if (message.serviceId !== "0") {
      writer.uint32(16).int64(message.serviceId);
    }
    if (message.checksTotal !== "0") {
      writer.uint32(24).int64(message.checksTotal);
    }
    if (message.checksPassed !== "0") {
      writer.uint32(32).int64(message.checksPassed);
    }
    for (const v of message.checkStatuses) {
      TeamServiceState_CheckStatus.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.points !== 0) {
      writer.uint32(49).double(message.points);
    }
    if (message.flagsStolen !== "0") {
      writer.uint32(56).int64(message.flagsStolen);
    }
    if (message.flagsLost !== "0") {
      writer.uint32(64).int64(message.flagsLost);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Scoreboard_TeamServiceState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScoreboard_TeamServiceState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.teamId = reader.int64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.serviceId = reader.int64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.checksTotal = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.checksPassed = reader.int64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.checkStatuses.push(TeamServiceState_CheckStatus.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.points = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.flagsStolen = reader.int64().toString();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.flagsLost = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  // encodeTransform encodes a source of message objects.
  // Transform<Scoreboard_TeamServiceState, Uint8Array>
  async *encodeTransform(
    source:
      | AsyncIterable<Scoreboard_TeamServiceState | Scoreboard_TeamServiceState[]>
      | Iterable<Scoreboard_TeamServiceState | Scoreboard_TeamServiceState[]>,
  ): AsyncIterable<Uint8Array> {
    for await (const pkt of source) {
      if (globalThis.Array.isArray(pkt)) {
        for (const p of (pkt as any)) {
          yield* [Scoreboard_TeamServiceState.encode(p).finish()];
        }
      } else {
        yield* [Scoreboard_TeamServiceState.encode(pkt as any).finish()];
      }
    }
  },

  // decodeTransform decodes a source of encoded messages.
  // Transform<Uint8Array, Scoreboard_TeamServiceState>
  async *decodeTransform(
    source: AsyncIterable<Uint8Array | Uint8Array[]> | Iterable<Uint8Array | Uint8Array[]>,
  ): AsyncIterable<Scoreboard_TeamServiceState> {
    for await (const pkt of source) {
      if (globalThis.Array.isArray(pkt)) {
        for (const p of (pkt as any)) {
          yield* [Scoreboard_TeamServiceState.decode(p)];
        }
      } else {
        yield* [Scoreboard_TeamServiceState.decode(pkt as any)];
      }
    }
  },

  fromJSON(object: any): Scoreboard_TeamServiceState {
    return {
      teamId: isSet(object.teamId)
        ? globalThis.String(object.teamId)
        : isSet(object.team_id)
        ? globalThis.String(object.team_id)
        : "0",
      serviceId: isSet(object.serviceId)
        ? globalThis.String(object.serviceId)
        : isSet(object.service_id)
        ? globalThis.String(object.service_id)
        : "0",
      checksTotal: isSet(object.checksTotal)
        ? globalThis.String(object.checksTotal)
        : isSet(object.checks_total)
        ? globalThis.String(object.checks_total)
        : "0",
      checksPassed: isSet(object.checksPassed)
        ? globalThis.String(object.checksPassed)
        : isSet(object.checks_passed)
        ? globalThis.String(object.checks_passed)
        : "0",
      checkStatuses: globalThis.Array.isArray(object?.checkStatuses)
        ? object.checkStatuses.map((e: any) => TeamServiceState_CheckStatus.fromJSON(e))
        : globalThis.Array.isArray(object?.check_statuses)
        ? object.check_statuses.map((e: any) => TeamServiceState_CheckStatus.fromJSON(e))
        : [],
      points: isSet(object.points) ? globalThis.Number(object.points) : 0,
      flagsStolen: isSet(object.flagsStolen)
        ? globalThis.String(object.flagsStolen)
        : isSet(object.flags_stolen)
        ? globalThis.String(object.flags_stolen)
        : "0",
      flagsLost: isSet(object.flagsLost)
        ? globalThis.String(object.flagsLost)
        : isSet(object.flags_lost)
        ? globalThis.String(object.flags_lost)
        : "0",
    };
  },

  toJSON(message: Scoreboard_TeamServiceState): unknown {
    const obj: any = {};
    if (message.teamId !== "0") {
      obj.teamId = message.teamId;
    }
    if (message.serviceId !== "0") {
      obj.serviceId = message.serviceId;
    }
    if (message.checksTotal !== "0") {
      obj.checksTotal = message.checksTotal;
    }
    if (message.checksPassed !== "0") {
      obj.checksPassed = message.checksPassed;
    }
    if (message.checkStatuses?.length) {
      obj.checkStatuses = message.checkStatuses.map((e) => TeamServiceState_CheckStatus.toJSON(e));
    }
    if (message.points !== 0) {
      obj.points = message.points;
    }
    if (message.flagsStolen !== "0") {
      obj.flagsStolen = message.flagsStolen;
    }
    if (message.flagsLost !== "0") {
      obj.flagsLost = message.flagsLost;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Scoreboard_TeamServiceState>, I>>(base?: I): Scoreboard_TeamServiceState {
    return Scoreboard_TeamServiceState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Scoreboard_TeamServiceState>, I>>(object: I): Scoreboard_TeamServiceState {
    const message = createBaseScoreboard_TeamServiceState();
    message.teamId = object.teamId ?? "0";
    message.serviceId = object.serviceId ?? "0";
    message.checksTotal = object.checksTotal ?? "0";
    message.checksPassed = object.checksPassed ?? "0";
    message.checkStatuses = object.checkStatuses?.map((e) => TeamServiceState_CheckStatus.fromPartial(e)) || [];
    message.points = object.points ?? 0;
    message.flagsStolen = object.flagsStolen ?? "0";
    message.flagsLost = object.flagsLost ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  encodeTransform(source: AsyncIterable<T | T[]> | Iterable<T | T[]>): AsyncIterable<Uint8Array>;
  decodeTransform(
    source: AsyncIterable<Uint8Array | Uint8Array[]> | Iterable<Uint8Array | Uint8Array[]>,
  ): AsyncIterable<T>;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
