// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: data/teams/teams.proto

package teams

import (
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *Team_Batch) CloneVT() *Team_Batch {
	if m == nil {
		return (*Team_Batch)(nil)
	}
	r := new(Team_Batch)
	if rhs := m.Teams; rhs != nil {
		tmpContainer := make([]*Team, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Teams = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Team_Batch) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *Team) CloneVT() *Team {
	if m == nil {
		return (*Team)(nil)
	}
	r := new(Team)
	r.Id = m.Id
	r.Name = m.Name
	r.Address = m.Address
	r.Token = m.Token
	if rhs := m.Labels; rhs != nil {
		tmpContainer := make(map[string]string, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v
		}
		r.Labels = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Team) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *ListRequest) CloneVT() *ListRequest {
	if m == nil {
		return (*ListRequest)(nil)
	}
	r := new(ListRequest)
	r.Version = m.Version.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *ListRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *ListResponse) CloneVT() *ListResponse {
	if m == nil {
		return (*ListResponse)(nil)
	}
	r := new(ListResponse)
	r.Version = m.Version.CloneVT()
	if rhs := m.Teams; rhs != nil {
		tmpContainer := make([]*Team, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Teams = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *ListResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *CreateBatchRequest) CloneVT() *CreateBatchRequest {
	if m == nil {
		return (*CreateBatchRequest)(nil)
	}
	r := new(CreateBatchRequest)
	if rhs := m.Teams; rhs != nil {
		tmpContainer := make([]*Team, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Teams = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *CreateBatchRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *CreateBatchResponse) CloneVT() *CreateBatchResponse {
	if m == nil {
		return (*CreateBatchResponse)(nil)
	}
	r := new(CreateBatchResponse)
	if rhs := m.Teams; rhs != nil {
		tmpContainer := make([]*Team, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Teams = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *CreateBatchResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}
