// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/teams/teams.proto

package teams

import (
	version "github.com/c4t-but-s4d/fastad/pkg/proto/data/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_data_teams_teams_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_data_teams_teams_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_data_teams_teams_proto_rawDescGZIP(), []int{0}
}

func (x *Team) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Team) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Team) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Team) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *version.Version       `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_data_teams_teams_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_teams_teams_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_data_teams_teams_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	Version       *version.Version       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_data_teams_teams_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_teams_teams_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_data_teams_teams_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ListResponse) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type CreateBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBatchRequest) Reset() {
	*x = CreateBatchRequest{}
	mi := &file_data_teams_teams_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchRequest) ProtoMessage() {}

func (x *CreateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_teams_teams_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateBatchRequest) Descriptor() ([]byte, []int) {
	return file_data_teams_teams_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBatchRequest) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type CreateBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBatchResponse) Reset() {
	*x = CreateBatchResponse{}
	mi := &file_data_teams_teams_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchResponse) ProtoMessage() {}

func (x *CreateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_teams_teams_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateBatchResponse) Descriptor() ([]byte, []int) {
	return file_data_teams_teams_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBatchResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_data_teams_teams_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_teams_teams_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_data_teams_teams_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Team          *Team                  `protobuf:"bytes,1,opt,name=team,proto3" json:"team,omitempty"`
	Version       *version.Version       `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_data_teams_teams_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_teams_teams_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_data_teams_teams_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetTeam() *Team {
	if x != nil {
		return x.Team
	}
	return nil
}

func (x *UpdateResponse) GetVersion() *version.Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type Team_Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*Team                `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Team_Batch) Reset() {
	*x = Team_Batch{}
	mi := &file_data_teams_teams_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team_Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team_Batch) ProtoMessage() {}

func (x *Team_Batch) ProtoReflect() protoreflect.Message {
	mi := &file_data_teams_teams_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team_Batch.ProtoReflect.Descriptor instead.
func (*Team_Batch) Descriptor() ([]byte, []int) {
	return file_data_teams_teams_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Team_Batch) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

var File_data_teams_teams_proto protoreflect.FileDescriptor

const file_data_teams_teams_proto_rawDesc = "" +
	"\n" +
	"\x16data/teams/teams.proto\x12\n" +
	"data.teams\x1a\x1adata/version/version.proto\"\x9b\x02\n" +
	"\x04Team\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x124\n" +
	"\x06labels\x18\x05 \x03(\v2\x1c.data.teams.Team.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x1a/\n" +
	"\x05Batch\x12&\n" +
	"\x05teams\x18\x01 \x03(\v2\x10.data.teams.TeamR\x05teams\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\vListRequest\x12/\n" +
	"\aversion\x18\x01 \x01(\v2\x15.data.version.VersionR\aversion\"g\n" +
	"\fListResponse\x12&\n" +
	"\x05teams\x18\x01 \x03(\v2\x10.data.teams.TeamR\x05teams\x12/\n" +
	"\aversion\x18\x02 \x01(\v2\x15.data.version.VersionR\aversion\"<\n" +
	"\x12CreateBatchRequest\x12&\n" +
	"\x05teams\x18\x01 \x03(\v2\x10.data.teams.TeamR\x05teams\"=\n" +
	"\x13CreateBatchResponse\x12&\n" +
	"\x05teams\x18\x01 \x03(\v2\x10.data.teams.TeamR\x05teams\"\x82\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\"g\n" +
	"\x0eUpdateResponse\x12$\n" +
	"\x04team\x18\x01 \x01(\v2\x10.data.teams.TeamR\x04team\x12/\n" +
	"\aversion\x18\x02 \x01(\v2\x15.data.version.VersionR\aversionB\x99\x01\n" +
	"\x0ecom.data.teamsB\n" +
	"TeamsProtoP\x01Z2github.com/c4t-but-s4d/fastad/pkg/proto/data/teams\xa2\x02\x03DTX\xaa\x02\n" +
	"Data.Teams\xca\x02\n" +
	"Data\\Teams\xe2\x02\x16Data\\Teams\\GPBMetadata\xea\x02\vData::Teamsb\x06proto3"

var (
	file_data_teams_teams_proto_rawDescOnce sync.Once
	file_data_teams_teams_proto_rawDescData []byte
)

func file_data_teams_teams_proto_rawDescGZIP() []byte {
	file_data_teams_teams_proto_rawDescOnce.Do(func() {
		file_data_teams_teams_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_teams_teams_proto_rawDesc), len(file_data_teams_teams_proto_rawDesc)))
	})
	return file_data_teams_teams_proto_rawDescData
}

var file_data_teams_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_data_teams_teams_proto_goTypes = []any{
	(*Team)(nil),                // 0: data.teams.Team
	(*ListRequest)(nil),         // 1: data.teams.ListRequest
	(*ListResponse)(nil),        // 2: data.teams.ListResponse
	(*CreateBatchRequest)(nil),  // 3: data.teams.CreateBatchRequest
	(*CreateBatchResponse)(nil), // 4: data.teams.CreateBatchResponse
	(*UpdateRequest)(nil),       // 5: data.teams.UpdateRequest
	(*UpdateResponse)(nil),      // 6: data.teams.UpdateResponse
	(*Team_Batch)(nil),          // 7: data.teams.Team.Batch
	nil,                         // 8: data.teams.Team.LabelsEntry
	(*version.Version)(nil),     // 9: data.version.Version
}
var file_data_teams_teams_proto_depIdxs = []int32{
	8, // 0: data.teams.Team.labels:type_name -> data.teams.Team.LabelsEntry
	9, // 1: data.teams.ListRequest.version:type_name -> data.version.Version
	0, // 2: data.teams.ListResponse.teams:type_name -> data.teams.Team
	9, // 3: data.teams.ListResponse.version:type_name -> data.version.Version
	0, // 4: data.teams.CreateBatchRequest.teams:type_name -> data.teams.Team
	0, // 5: data.teams.CreateBatchResponse.teams:type_name -> data.teams.Team
	0, // 6: data.teams.UpdateResponse.team:type_name -> data.teams.Team
	9, // 7: data.teams.UpdateResponse.version:type_name -> data.version.Version
	0, // 8: data.teams.Team.Batch.teams:type_name -> data.teams.Team
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_data_teams_teams_proto_init() }
func file_data_teams_teams_proto_init() {
	if File_data_teams_teams_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_teams_teams_proto_rawDesc), len(file_data_teams_teams_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_teams_teams_proto_goTypes,
		DependencyIndexes: file_data_teams_teams_proto_depIdxs,
		MessageInfos:      file_data_teams_teams_proto_msgTypes,
	}.Build()
	File_data_teams_teams_proto = out.File
	file_data_teams_teams_proto_goTypes = nil
	file_data_teams_teams_proto_depIdxs = nil
}
