// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: data/teams/teams.proto

package teams

import (
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *Team_Batch) CloneVT() *Team_Batch {
	if m == nil {
		return (*Team_Batch)(nil)
	}
	r := new(Team_Batch)
	if rhs := m.Teams; rhs != nil {
		tmpContainer := make([]*Team, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Teams = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Team_Batch) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *Team) CloneVT() *Team {
	if m == nil {
		return (*Team)(nil)
	}
	r := new(Team)
	r.Id = m.Id
	r.Name = m.Name
	r.Address = m.Address
	r.Token = m.Token
	if rhs := m.Labels; rhs != nil {
		tmpContainer := make(map[string]string, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v
		}
		r.Labels = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Team) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *ListRequest) CloneVT() *ListRequest {
	if m == nil {
		return (*ListRequest)(nil)
	}
	r := new(ListRequest)
	r.Version = m.Version.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *ListRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *ListResponse) CloneVT() *ListResponse {
	if m == nil {
		return (*ListResponse)(nil)
	}
	r := new(ListResponse)
	r.Version = m.Version.CloneVT()
	if rhs := m.Teams; rhs != nil {
		tmpContainer := make([]*Team, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Teams = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *ListResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *CreateBatchRequest) CloneVT() *CreateBatchRequest {
	if m == nil {
		return (*CreateBatchRequest)(nil)
	}
	r := new(CreateBatchRequest)
	if rhs := m.Teams; rhs != nil {
		tmpContainer := make([]*Team, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Teams = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *CreateBatchRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *CreateBatchResponse) CloneVT() *CreateBatchResponse {
	if m == nil {
		return (*CreateBatchResponse)(nil)
	}
	r := new(CreateBatchResponse)
	if rhs := m.Teams; rhs != nil {
		tmpContainer := make([]*Team, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.Teams = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *CreateBatchResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (this *Team_Batch) EqualVT(that *Team_Batch) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Teams) != len(that.Teams) {
		return false
	}
	for i, vx := range this.Teams {
		vy := that.Teams[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Team{}
			}
			if q == nil {
				q = &Team{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Team_Batch) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*Team_Batch)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Team) EqualVT(that *Team) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Id != that.Id {
		return false
	}
	if this.Name != that.Name {
		return false
	}
	if this.Address != that.Address {
		return false
	}
	if this.Token != that.Token {
		return false
	}
	if len(this.Labels) != len(that.Labels) {
		return false
	}
	for i, vx := range this.Labels {
		vy, ok := that.Labels[i]
		if !ok {
			return false
		}
		if vx != vy {
			return false
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Team) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*Team)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ListRequest) EqualVT(that *ListRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.Version.EqualVT(that.Version) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ListRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*ListRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *ListResponse) EqualVT(that *ListResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Teams) != len(that.Teams) {
		return false
	}
	for i, vx := range this.Teams {
		vy := that.Teams[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Team{}
			}
			if q == nil {
				q = &Team{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if !this.Version.EqualVT(that.Version) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *ListResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*ListResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *CreateBatchRequest) EqualVT(that *CreateBatchRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Teams) != len(that.Teams) {
		return false
	}
	for i, vx := range this.Teams {
		vy := that.Teams[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Team{}
			}
			if q == nil {
				q = &Team{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CreateBatchRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*CreateBatchRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *CreateBatchResponse) EqualVT(that *CreateBatchResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Teams) != len(that.Teams) {
		return false
	}
	for i, vx := range this.Teams {
		vy := that.Teams[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Team{}
			}
			if q == nil {
				q = &Team{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *CreateBatchResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*CreateBatchResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
