// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scoreboard/scoreboard.proto

package scoreboard

import (
	slac "github.com/c4t-but-s4d/fastad/pkg/proto/slac"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scoreboard struct {
	state             protoimpl.MessageState         `protogen:"open.v1"`
	TeamServiceStates []*Scoreboard_TeamServiceState `protobuf:"bytes,1,rep,name=team_service_states,json=teamServiceStates,proto3" json:"team_service_states,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Scoreboard) Reset() {
	*x = Scoreboard{}
	mi := &file_scoreboard_scoreboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scoreboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scoreboard) ProtoMessage() {}

func (x *Scoreboard) ProtoReflect() protoreflect.Message {
	mi := &file_scoreboard_scoreboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scoreboard.ProtoReflect.Descriptor instead.
func (*Scoreboard) Descriptor() ([]byte, []int) {
	return file_scoreboard_scoreboard_proto_rawDescGZIP(), []int{0}
}

func (x *Scoreboard) GetTeamServiceStates() []*Scoreboard_TeamServiceState {
	if x != nil {
		return x.TeamServiceStates
	}
	return nil
}

type Scoreboard_TeamServiceState struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TeamId    int64                  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ServiceId int64                  `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// From slac.
	ChecksTotal   int64                                `protobuf:"varint,3,opt,name=checks_total,json=checksTotal,proto3" json:"checks_total,omitempty"`
	ChecksPassed  int64                                `protobuf:"varint,4,opt,name=checks_passed,json=checksPassed,proto3" json:"checks_passed,omitempty"`
	CheckStatuses []*slac.TeamServiceState_CheckStatus `protobuf:"bytes,5,rep,name=check_statuses,json=checkStatuses,proto3" json:"check_statuses,omitempty"`
	// From receiver.
	Points        float64 `protobuf:"fixed64,6,opt,name=points,proto3" json:"points,omitempty"`
	FlagsStolen   int64   `protobuf:"varint,7,opt,name=flags_stolen,json=flagsStolen,proto3" json:"flags_stolen,omitempty"`
	FlagsLost     int64   `protobuf:"varint,8,opt,name=flags_lost,json=flagsLost,proto3" json:"flags_lost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scoreboard_TeamServiceState) Reset() {
	*x = Scoreboard_TeamServiceState{}
	mi := &file_scoreboard_scoreboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scoreboard_TeamServiceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scoreboard_TeamServiceState) ProtoMessage() {}

func (x *Scoreboard_TeamServiceState) ProtoReflect() protoreflect.Message {
	mi := &file_scoreboard_scoreboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scoreboard_TeamServiceState.ProtoReflect.Descriptor instead.
func (*Scoreboard_TeamServiceState) Descriptor() ([]byte, []int) {
	return file_scoreboard_scoreboard_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Scoreboard_TeamServiceState) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *Scoreboard_TeamServiceState) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *Scoreboard_TeamServiceState) GetChecksTotal() int64 {
	if x != nil {
		return x.ChecksTotal
	}
	return 0
}

func (x *Scoreboard_TeamServiceState) GetChecksPassed() int64 {
	if x != nil {
		return x.ChecksPassed
	}
	return 0
}

func (x *Scoreboard_TeamServiceState) GetCheckStatuses() []*slac.TeamServiceState_CheckStatus {
	if x != nil {
		return x.CheckStatuses
	}
	return nil
}

func (x *Scoreboard_TeamServiceState) GetPoints() float64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *Scoreboard_TeamServiceState) GetFlagsStolen() int64 {
	if x != nil {
		return x.FlagsStolen
	}
	return 0
}

func (x *Scoreboard_TeamServiceState) GetFlagsLost() int64 {
	if x != nil {
		return x.FlagsLost
	}
	return 0
}

var File_scoreboard_scoreboard_proto protoreflect.FileDescriptor

const file_scoreboard_scoreboard_proto_rawDesc = "" +
	"\n" +
	"\x1bscoreboard/scoreboard.proto\x12\n" +
	"scoreboard\x1a\x0fslac/slac.proto\"\x9f\x03\n" +
	"\n" +
	"Scoreboard\x12W\n" +
	"\x13team_service_states\x18\x01 \x03(\v2'.scoreboard.Scoreboard.TeamServiceStateR\x11teamServiceStates\x1a\xb7\x02\n" +
	"\x10TeamServiceState\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x03R\x06teamId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x03R\tserviceId\x12!\n" +
	"\fchecks_total\x18\x03 \x01(\x03R\vchecksTotal\x12#\n" +
	"\rchecks_passed\x18\x04 \x01(\x03R\fchecksPassed\x12I\n" +
	"\x0echeck_statuses\x18\x05 \x03(\v2\".slac.TeamServiceState.CheckStatusR\rcheckStatuses\x12\x16\n" +
	"\x06points\x18\x06 \x01(\x01R\x06points\x12!\n" +
	"\fflags_stolen\x18\a \x01(\x03R\vflagsStolen\x12\x1d\n" +
	"\n" +
	"flags_lost\x18\b \x01(\x03R\tflagsLostB\x9d\x01\n" +
	"\x0ecom.scoreboardB\x0fScoreboardProtoP\x01Z2github.com/c4t-but-s4d/fastad/pkg/proto/scoreboard\xa2\x02\x03SXX\xaa\x02\n" +
	"Scoreboard\xca\x02\n" +
	"Scoreboard\xe2\x02\x16Scoreboard\\GPBMetadata\xea\x02\n" +
	"Scoreboardb\x06proto3"

var (
	file_scoreboard_scoreboard_proto_rawDescOnce sync.Once
	file_scoreboard_scoreboard_proto_rawDescData []byte
)

func file_scoreboard_scoreboard_proto_rawDescGZIP() []byte {
	file_scoreboard_scoreboard_proto_rawDescOnce.Do(func() {
		file_scoreboard_scoreboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scoreboard_scoreboard_proto_rawDesc), len(file_scoreboard_scoreboard_proto_rawDesc)))
	})
	return file_scoreboard_scoreboard_proto_rawDescData
}

var file_scoreboard_scoreboard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scoreboard_scoreboard_proto_goTypes = []any{
	(*Scoreboard)(nil),                        // 0: scoreboard.Scoreboard
	(*Scoreboard_TeamServiceState)(nil),       // 1: scoreboard.Scoreboard.TeamServiceState
	(*slac.TeamServiceState_CheckStatus)(nil), // 2: slac.TeamServiceState.CheckStatus
}
var file_scoreboard_scoreboard_proto_depIdxs = []int32{
	1, // 0: scoreboard.Scoreboard.team_service_states:type_name -> scoreboard.Scoreboard.TeamServiceState
	2, // 1: scoreboard.Scoreboard.TeamServiceState.check_statuses:type_name -> slac.TeamServiceState.CheckStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scoreboard_scoreboard_proto_init() }
func file_scoreboard_scoreboard_proto_init() {
	if File_scoreboard_scoreboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scoreboard_scoreboard_proto_rawDesc), len(file_scoreboard_scoreboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scoreboard_scoreboard_proto_goTypes,
		DependencyIndexes: file_scoreboard_scoreboard_proto_depIdxs,
		MessageInfos:      file_scoreboard_scoreboard_proto_msgTypes,
	}.Build()
	File_scoreboard_scoreboard_proto = out.File
	file_scoreboard_scoreboard_proto_goTypes = nil
	file_scoreboard_scoreboard_proto_depIdxs = nil
}
