package cmd

import (
	"bytes"
	"fmt"
	"path/filepath"
	"text/template"

	"github.com/c4t-but-s4d/fastad/internal/gameconfig"
)

type productionEnvTemplateContext struct {
	LogLevel      string
	PublicPort    int
	IntercomToken string
	CheckersDir   string

	DatabaseDSN string
	Temporal    TemporalPostgresConfig
}

const productionEnvTemplateData = `# FastAD production preset environment file
# This file was generated by FastAD setup
# Do not edit this file manually

# services
FASTAD_LOG_LEVEL={{ .LogLevel }}
FASTAD_POSTGRES_DSN={{ .DatabaseDSN }}
FASTAD_INTERCOM_TOKEN={{ .IntercomToken }}

# checkers
CHECKERS_DIR={{ .CheckersDir }}

# temporal
TEMPORAL_POSTGRES_USER={{ .Temporal.User }}
TEMPORAL_POSTGRES_PASSWORD={{ .Temporal.Password }}
TEMPORAL_POSTGRES_DATABASE={{ .Temporal.Database }}
TEMPORAL_POSTGRES_HOST={{ .Temporal.Host }}
TEMPORAL_POSTGRES_PORT={{ .Temporal.Port }}
TEMPORAL_POSTGRES_TLS={{ .Temporal.TLS }}
TEMPORAL_SKIP_DB_CREATE={{ .Temporal.SkipDBCreate }}

# caddy
CADDY_PORT={{ .PublicPort }}
`

var productionEnvTemplate = template.Must(template.New("productionEnv").Parse(productionEnvTemplateData))

func PresetProduction(root string, config *gameconfig.GameConfig) error {
	envContext := productionEnvTemplateContext{
		LogLevel:      config.FastAD.LogLevel,
		PublicPort:    config.FastAD.ListenPort,
		IntercomToken: config.FastAD.IntercomToken,
	}

	checkersPath := config.Game.CheckersBasePath
	if filepath.IsAbs(checkersPath) {
		relPath, err := filepath.Rel(root, checkersPath)
		if err == nil {
			checkersPath = relPath
		}
	}
	envContext.CheckersDir = checkersPath

	startPostgres := true
	if config.Database != nil && config.Database.ExternalDSN != "" {
		envContext.DatabaseDSN = config.Database.ExternalDSN
		startPostgres = false
	} else {
		envContext.DatabaseDSN = "postgres://fastad:fastad@postgres:5432/fastad?sslmode=disable"
	}

	startTemporalPostgres := true
	if config.Database != nil && config.Database.TemporalExternalDSN != "" {
		var err error
		envContext.Temporal, err = ParseTemporalDSN(config.Database.TemporalExternalDSN)
		if err != nil {
			return fmt.Errorf("parsing temporal external dsn: %w", err)
		}
		startTemporalPostgres = false
	} else {
		envContext.Temporal = DefaultTemporalPostgresConfig()
	}

	var envContent bytes.Buffer
	if err := productionEnvTemplate.Execute(&envContent, envContext); err != nil {
		return fmt.Errorf("executing env template: %w", err)
	}

	envPath := filepath.Join(root, ".env")
	if err := WriteEnvFile(envPath, envContent.Bytes()); err != nil {
		return err
	}

	compose, err := LoadCompose(PresetComposePath(root, "production"))
	if err != nil {
		return err
	}

	if !startPostgres {
		compose.RemoveService("postgres")
		compose.RemoveDependsOn("migrator")
	}

	if !startTemporalPostgres {
		compose.RemoveService("temporal-postgres")
		compose.RemoveDependsOn("temporal-admin-tools")
	}

	config.Game.CheckersBasePath = "/checkers-scripts"
	for _, service := range config.Services {
		service.Checker.Path = filepath.Join(config.Game.CheckersBasePath, service.Checker.Path)
	}

	destCompose := filepath.Join(root, "compose.yml")
	return compose.Write(destCompose)
}
