// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: slac/slac_service.proto

package slac

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SlacService_GetState_FullMethodName = "/slac.SlacService/GetState"
)

// SlacServiceClient is the client API for SlacService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlacServiceClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
}

type slacServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSlacServiceClient(cc grpc.ClientConnInterface) SlacServiceClient {
	return &slacServiceClient{cc}
}

func (c *slacServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, SlacService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlacServiceServer is the server API for SlacService service.
// All implementations must embed UnimplementedSlacServiceServer
// for forward compatibility.
type SlacServiceServer interface {
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	mustEmbedUnimplementedSlacServiceServer()
}

// UnimplementedSlacServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSlacServiceServer struct{}

func (UnimplementedSlacServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedSlacServiceServer) mustEmbedUnimplementedSlacServiceServer() {}
func (UnimplementedSlacServiceServer) testEmbeddedByValue()                     {}

// UnsafeSlacServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlacServiceServer will
// result in compilation errors.
type UnsafeSlacServiceServer interface {
	mustEmbedUnimplementedSlacServiceServer()
}

func RegisterSlacServiceServer(s grpc.ServiceRegistrar, srv SlacServiceServer) {
	// If the following call pancis, it indicates UnimplementedSlacServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SlacService_ServiceDesc, srv)
}

func _SlacService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlacServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SlacService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlacServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SlacService_ServiceDesc is the grpc.ServiceDesc for SlacService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlacService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slac.SlacService",
	HandlerType: (*SlacServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _SlacService_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slac/slac_service.proto",
}
