// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: slac/slac_service.proto

package slac

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_slac_slac_service_proto protoreflect.FileDescriptor

const file_slac_slac_service_proto_rawDesc = "" +
	"\n" +
	"\x17slac/slac_service.proto\x12\x04slac\x1a\x0fslac/slac.proto2H\n" +
	"\vSlacService\x129\n" +
	"\bGetState\x12\x15.slac.GetStateRequest\x1a\x16.slac.GetStateResponseBz\n" +
	"\bcom.slacB\x10SlacServiceProtoP\x01Z,github.com/c4t-but-s4d/fastad/pkg/proto/slac\xa2\x02\x03SXX\xaa\x02\x04Slac\xca\x02\x04Slac\xe2\x02\x10Slac\\GPBMetadata\xea\x02\x04Slacb\x06proto3"

var file_slac_slac_service_proto_goTypes = []any{
	(*GetStateRequest)(nil),  // 0: slac.GetStateRequest
	(*GetStateResponse)(nil), // 1: slac.GetStateResponse
}
var file_slac_slac_service_proto_depIdxs = []int32{
	0, // 0: slac.SlacService.GetState:input_type -> slac.GetStateRequest
	1, // 1: slac.SlacService.GetState:output_type -> slac.GetStateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_slac_slac_service_proto_init() }
func file_slac_slac_service_proto_init() {
	if File_slac_slac_service_proto != nil {
		return
	}
	file_slac_slac_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slac_slac_service_proto_rawDesc), len(file_slac_slac_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slac_slac_service_proto_goTypes,
		DependencyIndexes: file_slac_slac_service_proto_depIdxs,
	}.Build()
	File_slac_slac_service_proto = out.File
	file_slac_slac_service_proto_goTypes = nil
	file_slac_slac_service_proto_depIdxs = nil
}
