// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: slac/slac.proto

package slac

import (
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *TeamServiceState_CheckStatus) CloneVT() *TeamServiceState_CheckStatus {
	if m == nil {
		return (*TeamServiceState_CheckStatus)(nil)
	}
	r := new(TeamServiceState_CheckStatus)
	r.Status = m.Status
	r.Message = m.Message
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *TeamServiceState_CheckStatus) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *TeamServiceState) CloneVT() *TeamServiceState {
	if m == nil {
		return (*TeamServiceState)(nil)
	}
	r := new(TeamServiceState)
	r.TeamId = m.TeamId
	r.ServiceId = m.ServiceId
	r.ChecksTotal = m.ChecksTotal
	r.ChecksPassed = m.ChecksPassed
	if rhs := m.CheckStatuses; rhs != nil {
		tmpContainer := make([]*TeamServiceState_CheckStatus, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.CheckStatuses = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *TeamServiceState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *State) CloneVT() *State {
	if m == nil {
		return (*State)(nil)
	}
	r := new(State)
	if rhs := m.TeamServiceStates; rhs != nil {
		tmpContainer := make([]*TeamServiceState, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.TeamServiceStates = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *State) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *GetStateRequest) CloneVT() *GetStateRequest {
	if m == nil {
		return (*GetStateRequest)(nil)
	}
	r := new(GetStateRequest)
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *GetStateRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *GetStateResponse) CloneVT() *GetStateResponse {
	if m == nil {
		return (*GetStateResponse)(nil)
	}
	r := new(GetStateResponse)
	r.State = m.State.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *GetStateResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}
