// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        (unknown)
// source: slac/slac.proto

package slac

import (
	checker "github.com/c4t-but-s4d/fastad/pkg/proto/checker"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamServiceState struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	TeamId        int64                           `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ServiceId     int64                           `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ChecksTotal   int64                           `protobuf:"varint,3,opt,name=checks_total,json=checksTotal,proto3" json:"checks_total,omitempty"`
	ChecksPassed  int64                           `protobuf:"varint,4,opt,name=checks_passed,json=checksPassed,proto3" json:"checks_passed,omitempty"`
	CheckStatuses []*TeamServiceState_CheckStatus `protobuf:"bytes,5,rep,name=check_statuses,json=checkStatuses,proto3" json:"check_statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamServiceState) Reset() {
	*x = TeamServiceState{}
	mi := &file_slac_slac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamServiceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamServiceState) ProtoMessage() {}

func (x *TeamServiceState) ProtoReflect() protoreflect.Message {
	mi := &file_slac_slac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamServiceState.ProtoReflect.Descriptor instead.
func (*TeamServiceState) Descriptor() ([]byte, []int) {
	return file_slac_slac_proto_rawDescGZIP(), []int{0}
}

func (x *TeamServiceState) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *TeamServiceState) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *TeamServiceState) GetChecksTotal() int64 {
	if x != nil {
		return x.ChecksTotal
	}
	return 0
}

func (x *TeamServiceState) GetChecksPassed() int64 {
	if x != nil {
		return x.ChecksPassed
	}
	return 0
}

func (x *TeamServiceState) GetCheckStatuses() []*TeamServiceState_CheckStatus {
	if x != nil {
		return x.CheckStatuses
	}
	return nil
}

type State struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TeamServiceStates []*TeamServiceState    `protobuf:"bytes,1,rep,name=team_service_states,json=teamServiceStates,proto3" json:"team_service_states,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_slac_slac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_slac_slac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_slac_slac_proto_rawDescGZIP(), []int{1}
}

func (x *State) GetTeamServiceStates() []*TeamServiceState {
	if x != nil {
		return x.TeamServiceStates
	}
	return nil
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_slac_slac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slac_slac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_slac_slac_proto_rawDescGZIP(), []int{2}
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_slac_slac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slac_slac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_slac_slac_proto_rawDescGZIP(), []int{3}
}

func (x *GetStateResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

type TeamServiceState_CheckStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        checker.Status         `protobuf:"varint,1,opt,name=status,proto3,enum=checker.Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamServiceState_CheckStatus) Reset() {
	*x = TeamServiceState_CheckStatus{}
	mi := &file_slac_slac_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamServiceState_CheckStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamServiceState_CheckStatus) ProtoMessage() {}

func (x *TeamServiceState_CheckStatus) ProtoReflect() protoreflect.Message {
	mi := &file_slac_slac_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamServiceState_CheckStatus.ProtoReflect.Descriptor instead.
func (*TeamServiceState_CheckStatus) Descriptor() ([]byte, []int) {
	return file_slac_slac_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TeamServiceState_CheckStatus) GetStatus() checker.Status {
	if x != nil {
		return x.Status
	}
	return checker.Status(0)
}

func (x *TeamServiceState_CheckStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_slac_slac_proto protoreflect.FileDescriptor

var file_slac_slac_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x6c, 0x61, 0x63, 0x2f, 0x73, 0x6c, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x73, 0x6c, 0x61, 0x63, 0x1a, 0x15, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72,
	0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf,
	0x02, 0x0a, 0x10, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x73, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x50, 0x61, 0x73,
	0x73, 0x65, 0x64, 0x12, 0x49, 0x0a, 0x0e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x6c,
	0x61, 0x63, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x65, 0x73, 0x1a, 0x50,
	0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x4f, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x46, 0x0a, 0x13, 0x74, 0x65, 0x61,
	0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x6c, 0x61, 0x63, 0x2e, 0x54, 0x65,
	0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x11,
	0x74, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x73, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x6c, 0x61, 0x63, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x73, 0x0a, 0x08, 0x63,
	0x6f, 0x6d, 0x2e, 0x73, 0x6c, 0x61, 0x63, 0x42, 0x09, 0x53, 0x6c, 0x61, 0x63, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x34, 0x74, 0x2d, 0x62, 0x75, 0x74, 0x2d, 0x73, 0x34, 0x64, 0x2f, 0x66, 0x61, 0x73,
	0x74, 0x61, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6c,
	0x61, 0x63, 0xa2, 0x02, 0x03, 0x53, 0x58, 0x58, 0xaa, 0x02, 0x04, 0x53, 0x6c, 0x61, 0x63, 0xca,
	0x02, 0x04, 0x53, 0x6c, 0x61, 0x63, 0xe2, 0x02, 0x10, 0x53, 0x6c, 0x61, 0x63, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x04, 0x53, 0x6c, 0x61, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_slac_slac_proto_rawDescOnce sync.Once
	file_slac_slac_proto_rawDescData = file_slac_slac_proto_rawDesc
)

func file_slac_slac_proto_rawDescGZIP() []byte {
	file_slac_slac_proto_rawDescOnce.Do(func() {
		file_slac_slac_proto_rawDescData = protoimpl.X.CompressGZIP(file_slac_slac_proto_rawDescData)
	})
	return file_slac_slac_proto_rawDescData
}

var file_slac_slac_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_slac_slac_proto_goTypes = []any{
	(*TeamServiceState)(nil),             // 0: slac.TeamServiceState
	(*State)(nil),                        // 1: slac.State
	(*GetStateRequest)(nil),              // 2: slac.GetStateRequest
	(*GetStateResponse)(nil),             // 3: slac.GetStateResponse
	(*TeamServiceState_CheckStatus)(nil), // 4: slac.TeamServiceState.CheckStatus
	(checker.Status)(0),                  // 5: checker.Status
}
var file_slac_slac_proto_depIdxs = []int32{
	4, // 0: slac.TeamServiceState.check_statuses:type_name -> slac.TeamServiceState.CheckStatus
	0, // 1: slac.State.team_service_states:type_name -> slac.TeamServiceState
	1, // 2: slac.GetStateResponse.state:type_name -> slac.State
	5, // 3: slac.TeamServiceState.CheckStatus.status:type_name -> checker.Status
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_slac_slac_proto_init() }
func file_slac_slac_proto_init() {
	if File_slac_slac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_slac_slac_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slac_slac_proto_goTypes,
		DependencyIndexes: file_slac_slac_proto_depIdxs,
		MessageInfos:      file_slac_slac_proto_msgTypes,
	}.Build()
	File_slac_slac_proto = out.File
	file_slac_slac_proto_rawDesc = nil
	file_slac_slac_proto_goTypes = nil
	file_slac_slac_proto_depIdxs = nil
}
