// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: slac/slac.proto

package slac

import (
	proto "google.golang.org/protobuf/proto"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

func (m *TeamServiceState_CheckStatus) CloneVT() *TeamServiceState_CheckStatus {
	if m == nil {
		return (*TeamServiceState_CheckStatus)(nil)
	}
	r := new(TeamServiceState_CheckStatus)
	r.Status = m.Status
	r.Message = m.Message
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *TeamServiceState_CheckStatus) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *TeamServiceState) CloneVT() *TeamServiceState {
	if m == nil {
		return (*TeamServiceState)(nil)
	}
	r := new(TeamServiceState)
	r.TeamId = m.TeamId
	r.ServiceId = m.ServiceId
	r.ChecksTotal = m.ChecksTotal
	r.ChecksPassed = m.ChecksPassed
	if rhs := m.CheckStatuses; rhs != nil {
		tmpContainer := make([]*TeamServiceState_CheckStatus, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.CheckStatuses = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *TeamServiceState) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *State) CloneVT() *State {
	if m == nil {
		return (*State)(nil)
	}
	r := new(State)
	if rhs := m.TeamServiceStates; rhs != nil {
		tmpContainer := make([]*TeamServiceState, len(rhs))
		for k, v := range rhs {
			tmpContainer[k] = v.CloneVT()
		}
		r.TeamServiceStates = tmpContainer
	}
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *State) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *GetStateRequest) CloneVT() *GetStateRequest {
	if m == nil {
		return (*GetStateRequest)(nil)
	}
	r := new(GetStateRequest)
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *GetStateRequest) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (m *GetStateResponse) CloneVT() *GetStateResponse {
	if m == nil {
		return (*GetStateResponse)(nil)
	}
	r := new(GetStateResponse)
	r.State = m.State.CloneVT()
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *GetStateResponse) CloneMessageVT() proto.Message {
	return m.CloneVT()
}

func (this *TeamServiceState_CheckStatus) EqualVT(that *TeamServiceState_CheckStatus) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.Status != that.Status {
		return false
	}
	if this.Message != that.Message {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *TeamServiceState_CheckStatus) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*TeamServiceState_CheckStatus)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *TeamServiceState) EqualVT(that *TeamServiceState) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.TeamId != that.TeamId {
		return false
	}
	if this.ServiceId != that.ServiceId {
		return false
	}
	if this.ChecksTotal != that.ChecksTotal {
		return false
	}
	if this.ChecksPassed != that.ChecksPassed {
		return false
	}
	if len(this.CheckStatuses) != len(that.CheckStatuses) {
		return false
	}
	for i, vx := range this.CheckStatuses {
		vy := that.CheckStatuses[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &TeamServiceState_CheckStatus{}
			}
			if q == nil {
				q = &TeamServiceState_CheckStatus{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *TeamServiceState) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*TeamServiceState)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *State) EqualVT(that *State) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.TeamServiceStates) != len(that.TeamServiceStates) {
		return false
	}
	for i, vx := range this.TeamServiceStates {
		vy := that.TeamServiceStates[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &TeamServiceState{}
			}
			if q == nil {
				q = &TeamServiceState{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *State) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*State)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *GetStateRequest) EqualVT(that *GetStateRequest) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *GetStateRequest) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*GetStateRequest)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *GetStateResponse) EqualVT(that *GetStateResponse) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if !this.State.EqualVT(that.State) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *GetStateResponse) EqualMessageVT(thatMsg proto.Message) bool {
	that, ok := thatMsg.(*GetStateResponse)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
