// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: data/services/services_service.proto

/* eslint-disable */

export const protobufPackage = "data.services";
