// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               unknown
// source: data/game_state/game_state_service.proto

/* eslint-disable */
import { type CallContext, type CallOptions } from "nice-grpc-common";
import {
  GetRequest,
  GetResponse,
  UpdateRequest,
  UpdateResponse,
  UpdateRoundRequest,
  UpdateRoundResponse,
} from "./game_state";

export const protobufPackage = "data.game_state";

export type GameStateServiceDefinition = typeof GameStateServiceDefinition;
export const GameStateServiceDefinition = {
  name: "GameStateService",
  fullName: "data.game_state.GameStateService",
  methods: {
    get: {
      name: "Get",
      requestType: GetRequest,
      requestStream: false,
      responseType: GetResponse,
      responseStream: false,
      options: {},
    },
    update: {
      name: "Update",
      requestType: UpdateRequest,
      requestStream: false,
      responseType: UpdateResponse,
      responseStream: false,
      options: {},
    },
    updateRound: {
      name: "UpdateRound",
      requestType: UpdateRoundRequest,
      requestStream: false,
      responseType: UpdateRoundResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface GameStateServiceImplementation<CallContextExt = {}> {
  get(request: GetRequest, context: CallContext & CallContextExt): Promise<DeepPartial<GetResponse>>;
  update(request: UpdateRequest, context: CallContext & CallContextExt): Promise<DeepPartial<UpdateResponse>>;
  updateRound(
    request: UpdateRoundRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<UpdateRoundResponse>>;
}

export interface GameStateServiceClient<CallOptionsExt = {}> {
  get(request: DeepPartial<GetRequest>, options?: CallOptions & CallOptionsExt): Promise<GetResponse>;
  update(request: DeepPartial<UpdateRequest>, options?: CallOptions & CallOptionsExt): Promise<UpdateResponse>;
  updateRound(
    request: DeepPartial<UpdateRoundRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<UpdateRoundResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;
