// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: data/game_state/game_state_service.proto

/* eslint-disable */

export const protobufPackage = "data.game_state";
