name: tests
on:
  push:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  checks: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run tests
        run: make test

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  lint-proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1.48.0

      - name: Lint proto
        run: make lint-proto

  lint-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: 'front/package.json'

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'front/.node-version'
          cache: 'pnpm'
          cache-dependency-path: 'front/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: front

      - name: Lint front
        run: make lint-front
